- examples/pages/basic/index.js
- examples/pages/semantic-ui/index.js
the basic and sementic-ui examples had the old item prop in the forwardProps
> Examples: update forwarded prop item -> value

- src/autocomplete.js
**What**:
Fixes https://github.com/paypal/react-autocompletely/issues/31
**Why**:
First arrow down event was not respecting defaultHighlightedIndex prop.
**How**:
Use defaultHighlightedIndex prop when menu first opens .
**Checklist**:
> fix autocomplete arrow down highlight

- README.md
- examples/pages/apollo/index.js
- examples/pages/axios-request/index.js
- examples/pages/basic/index.js
- examples/pages/react-instantsearch/index.js
- examples/pages/react-popper/index.js
- examples/pages/semantic-ui/index.js
- package.json
- src/__tests__/index.js
- src/autocomplete.js
- src/controller.js
- src/menu-status.js
- src/menu.js
**What**:
This allows users to always render the menu similar to the option here in [react-autosuggest](https://github.com/moroshko/react-autosuggest#alwaysRenderSuggestionsProp). It also keeps a clean DOM by rendering the status to the end of the document as well as switches `children` function props to be called `render` for better API clarity.
**Why**:
This will allow more complex menus and animations to be made by giving the user full control over rendering the `Menu` component. It's a little more work to hook `isOpen` up, but worth the benefit in my opinion. Plus you're already pulling things like `selectedItem` and `highlightedIndex` off.
I switched the `children` prop to `render` to follow conventions similar to React Router. After implementing just a returned `children` function, …
> feat(api): only return render prop from Menu component

- README.md
- examples/pages/semantic-ui/index.js
- src/autocomplete.js
- src/button.js
- src/input.js
- src/menu.js
**What**:
A `Button` component that applies proper ARIA attributes and allows controlling the opening and closing of the menu as well as keyboard navigation of the list of items.
**Why**:
This helps us build accessible dropdown + autocomplete solutions.
**How**:
I added a `Button` component that mimics some of the behavior of the `Input`.
**Checklist**:
Another addition to the API 😇 I think this will help with having an accessible button handy to control the `Menu`. I used it real quick in your semantic-ui demo and it worked nice 👌 applies all the proper ARIA attributes and allows for keyboard navigation.
> feat(component): added Button component to control Menu

- src/autocomplete.js
**What**:
Related to the discussion in https://github.com/paypal/react-autocompletely/issues/9.
**Why**:
It still didn't respect setting `null` when at beginning and moving the highlight backwards, or at the the end and moving the highlight forward. It also wasn't respecting `defaultHighlightedIndex` when the menu was opened.
**How**:
I reworked `changeHighlighedIndex` to move the `highlightedIndex` to `null` when appropriate. I also added calling the `setHighlightedIndex` method now when first opening the menu.
**Checklist**:
> better highlighting

- .eslintignore
- README.md
- src/autocomplete.js
- stories/config.js
- stories/examples/basic.js
**What**:
Removes the last opinion about the DOM. 
**Why**:
I already hit a snag where I wanted a custom top level component to integrate better in my UI kit and I think this might be better since it follows suite to the other functions like `getItemProps`.
**How**:
I was able to get around the `ref` issue by just allowing a prop called `refKey` to be passed when you need to forward the ref in a non-traditional way like `{ refKey: 'innerRef' }`. I'm not tied to the name of the prop, maybe `getRef` or something? After doing this I'm wondering if we can go back to just using refs for the other components. It's up to you though :)
**Checklist**:
> Only return child function

- README.md
This PR adds one small fix and one small improvement that I hope make the README code example easier for others to read.
- Syntax error: `style` was set on the div in a way that doesn't seem to be valid JSX (maybe there are some other Babel settings where this is valid?)
- I found the use of the variable name `value` in two places a bit confusing. At the top level, `value` refers to the string currently typed in the search field. Within the function provided to `map`, it instead refers to one of the items. I think renaming this second usage to `item` makes it clearer what the code is doing.
> Small improvements to README code example

- src/autocomplete.js
**What**:
Fix evaluation order (happens to me all the time ☺️)
**Why**:
We were getting the wrong initial value
**How**:
Adding brackets around ternary since they have a higher operator precedence than `||`.
**Checklist**:
> fix: wrong logic in constructor call

- .eslintrc
- README.md
- src/autocomplete.js
- stories/config.js
- stories/examples/basic.js
- stories/examples/controlled.js
This adds the concept of `state props` to enable a totally controlled component experience. It's actually quite awesome if I say so myself. 🕶
Feedback welcome!
Closes #80
**Checklist**:
cc @jgoux, this is what you're looking for I think :smile: I'd really appreciate a review!
> feat(stateProps): add the concept of state props

- README.md
- src/downshift.js
- stories/examples/apollo.js
- stories/examples/axios.js
- stories/examples/basic.js
- stories/examples/controlled.js
- stories/examples/react-instantsearch.js
- stories/examples/react-popper.js
- stories/examples/semantic-ui.js
**What**: This has a few breaking changes to the API. The biggest 2 are `getInputProps` now accepts `item` rather than `value` and `selectedValue` is now `selectedItem`.
**Why**: Really simplifies things. Closes #93, Closes #90, Closes #101, Closes #94
**How**: Coding... I guess. Watch the livestream later :wink:
**Checklist**:
> Remove references to `value` (except `inputValue`) & other improvement

- README.md
- src/__tests__/.eslintrc
- src/__tests__/downshift.get-item-props.js
- src/downshift.js
- src/utils.js
- stories/examples/basic.js
Closes #113
**What**: This looks up the tree to find the closest parent with the item id.
**Why**: This fixes an issue where if you have items with a nested structure the item would not be selected because the `target` did not have the `id` on it.
**How**: Refactor `getClosestScrollParent` into a generic `findParent` function and use that. This actually also fixed a bug in `getClosestScrollParent` where the `rootNode` was not passed recursively and the search would stop prematurely.
**Checklist**:
> fix(getItemProps): clicking anywhere in the item selects the item

- README.md
- src/__tests__/downshift.misc.js
- src/downshift.js
- src/utils.js
**What**: fix(onStateChange): only call the handler when state actually changes
Also adds a second parameter that has all the state
**Why**: Closes #123
**How**: Refactoring `internalSetState`
**Checklist**:
> fix(onStateChange): only call the handler when state actually changes

- src/__tests__/downshift.lifecycle.js
- src/downshift.js
**What**: This initializes the `inputValue` based on the `selectedItem`
**Why**: So if `selectedItem` is given as a prop, the `inputValue` is set based on `this.props.itemToString`. Closes #119
**How**: Updated the constructor and fixed a bug in `getState`.
**Checklist**:
> fix(inputValue): initilize the inputValue correctly

- README.md
- src/__tests__/downshift.get-input-props.js
- src/downshift.js
- stories/examples/apollo.js
- stories/examples/basic.js
- stories/examples/controlled.js
- stories/examples/react-instantsearch.js
- stories/examples/react-popper.js
**What**: Removes `previousItem` from the `onChange` callback and instead calls it with just `selectItem, allState`.
**Why**: Closes #130
**How**: simplify things a bit and update examples
**Checklist**:
> feat(onChange): remove previousItem from onChange callback

- .gitignore
- package-scripts.js
- src/__tests__/downshift.misc.js
- src/downshift.js
Before, it was calling `onChange` any time there was a
`internalSetState({selectedItem})`
> fix(onChange): only call `onChange` when the selection changes

- CONTRIBUTING.md
- src/__tests__/utils.scroll-into-view.js
- src/utils.js
**What**: scrolling offsets now take bottom border into account
**Why**:
Auto scrolling does not offset enough when using larger borders.
Example:
(dropdown borders exaggerated to demonstrate issue)
***Before***:
***After***:
**How**:
Added a check for border bottom to the `scrollIntoView` function
**Checklist**:
> fix(scrollIntoView): take bottom borders into account when scrolling

- test/basic.test.tsx
- typings/index.d.ts
This PR updates the TypeScript definitions for the `onChange` and `onStateChange` handlers introduced in 620a3ad5e4f50dece867ae9989174a8b35104fb3
- Removed `previousItem` from `onChange` and returns only the `selectedItem` itself
- Both `onChange` and `onStateChange` accepts a 2nd parameter `allState`
> update typings for onChange and onStateChange

- README.md
- src/__tests__/downshift.misc.js
- src/downshift.js
- stories/examples/react-autosuggest.js
**What**: add `onUserAction` to be notified whenever state could be updated
**Why**: This allows us to gate `onStateChange` to only be called when state actually changed. Closes #148 
**How**:
- Pass a `type` 100% of the time (default to `unknown`)
- gate calling `onStateChange`
- always call `onUserAction`.
Not sure I love the name `onUserAction` because this will be called even if things happen programmatically. Hence this is not documented yet...
**Checklist**:
> feat: add `onUserAction` to be notified whenever state could be updated

- README.md
**What**: Update Examples to include Redux and React Router
**Why**: They were missing and the README had call outs to add :smile:
**How**: Used codesandbox
**Checklist**:
> Update README to include redux and react-router examples

- README.md
- src/__tests__/downshift.misc.js
- src/__tests__/downshift.props.js
- src/downshift.js
**What**: calls `onStateChange`, `onChange`, and `onUserAction` with all
the downshift state and helpers.
**Why**: Make it so people don't need to use the downshift reference.
Closes #155
**How**: Instead of calling `this.getState()`, call
`this.getDownshiftStateAndHelpers()`.
**Checklist**:
> feat(onChange): call with all downshift state and helpers

- rollup.config.js
**What**: Use `preact` as the global for the UMD preact bundle instead of `react`.
**Why**:
The UMD build of preact references a `global.React`:
```js
// umd
(function (global, factory) {
typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('preact')) :
typeof define === 'function' && define.amd ? define(['preact'], factory) :
(global.Downshift = factory(global.React));
}(this, (function (React) { 'use strict';
/* ... */
})));
```
https://unpkg.com/downshift@1.3.0/dist/downshift.preact.umd.js
When targeting preact, `rollup-plugin-alias` changes all `react` module references to `preact`:
```js
// cjs
var React = require('preact');
```
`preact` isn't provided as a global to rollup, so for the UMD build, [rollup guesses `React` based off of the …
> fix(preact): fix umd export for preact

- stories/config.js
- stories/examples/multiple.js
**What**:
Adds an example of a multiple (aka tagging) autocomplete with Downshift.
Preview (GIF):
**Why**:
No examples of a multiple autocomplete yet.
Prior discussion in #139.
**How**:
- Selected items are ignored - they're not highlighted by Downshift
- Backspace to delete last item added
- Input value is controlled so we can clear them
**Checklist**:
It may be lacking some simple convenience such as focusing automatically to the input when any part of the box is clicked.
> Add multiple example

- test/basic.test.tsx
- test/custom.test.tsx
TypeScript tests should not import `ChangeOptions`, since that property has been removed.
**What**: Fix TypeScript tests
**Why**: There was a build issue in https://github.com/paypal/downshift/pull/165
**How**: Remove references to removed `ChangeOptions`
**Checklist**:
> Fix TS build issue

- src/__tests__/utils.pick-state.js
- src/downshift.js
- src/utils.js
Make `toggleMenu` and friends more user-friendly by only picking out
state that is relevant to downshift, allowing users to use them as event
event handlers. See #182.
**What**: Make `toggleMenu` and friends more user-friendly.
**Why**:  See #182.
**How**: Add `pickState` and call it whenever we are about to spread `otherStateToSet` into `internalSetState`
**Checklist**:
Additional comments:
1. When I initially pulled the most recent from master, `npm run validate` failed.
FAIL  other\__tests__\build.js
● Test suite failed to run
Cannot find module '../../dist/downshift.es' from 'build.js'
at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
at Object.<anonymous> (other/__tests__/build.js:14:18)
FAIL  other\__tests__\preact.js
● Test suite failed to run
Cannot find …
> feat(pickState): only pick relevant state

- README.md
- src/__tests__/downshift.misc.js
- src/downshift.js
- typings/index.d.ts
**What**:
Solves https://github.com/paypal/downshift/issues/186
**Why**:
No way to clear tracked items from children.
**How**:
Added `clearItems` as property method which sets `this.items = []`
**Checklist**:
> feat(actions): add clear items action

- stories/examples/react-autosuggest.js
**What**:
Fixes warning: `value prop on input should not be null`. On escape event, set selected to empty string, not null.
**Why**:
Fixes this bug (which I can't repro every time for some reason but happens often. This seems to have fixed it though).
> reset selected as empty str, not null

- stories/examples/multiple.js
**What**: Use `selectedItem` in the multiple example
**Why**: Because I got some weird behaviour with the last item not being added
**How**: Use `selectedItem` instead of `values` directly
**Checklist**:
To reproduce: in the [multiple story](https://downshift.netlify.com/?selectedKind=Examples&selectedStory=multiple&full=0&down=1&left=1&panelRight=0), try adding all the colors, then remove the last one. Try re-adding it, and notice it doesn't get added. I guess downshift does some _magic behind the scenes™_, keeping the selected items in sync. According to the [multiple example in the readme](https://codesandbox.io/s/W6gyJ30kn), you can use `selectedItem` even tho it's kind of weird that it can have multiple values given the singular name ;)
> Use selectedItem for values in multiple example story

- src/__tests__/__snapshots__/downshift.get-root-props.js.snap
- src/__tests__/downshift.get-root-props.js
- src/downshift.js
- src/utils.js
**What**: This swaps our document querying stuff from the root element with a more explicit `onClick` handler on the items.
**Why**: It probably should have always been this way...
**How**: Make the changes, see only one test broke, turns out that's unnecessary with the changes now so we can delete it.
**Checklist**:
This should also make it easier to implement #185 :+1:
cc @gricard and @Swizec :smile:
> feat: use onClick handler on items rather than on root

- src/__tests__/downshift.get-item-props.js
- src/downshift.js
**What**:
Fixes #194
**Why**:
As a user I'd expect `highlightedIndex` to always have the value that I initially set it to, after selecting an item. I.e. react-select also works like this. It allows the user to quickly hit enter when the right item is the first in the list.
**How**:
`highlightedIndex` was always set to `null` when selecting an item. I changed that to be set to the `defaultHighlightedIndex`prop.
**Checklist**:
> Reset highlightedIndex to defaultHighlightIndex after selecting item

- other/__tests__/build.js
- package.json
**What**: Updating `jsnext:main` and `module` in package.json to use the correct path to the ES module.
**Why**:  I was getting errors in ESLint because the [import plugin](https://github.com/benmosher/eslint-plugin-import) was unable to find the module. My project actually built just fine, but the linting failed. This change makes ESLint happy.
**How**: Changing those fields in the package file.
**Checklist**:
The build test was also failing because it had an incorrect path to the module, so I fixed that as well. Running `npm run build-and-test` had two failures: one for this problem, and one for the preact build. I tried fixing the preact path as well but then got other failures I wasn't sure how to fix.
> fix(esm): fix path to ES module

- other/ssr/__tests__/index.js
- other/ssr/jest.config.js
- src/downshift.js
**What**: adds a `typeof` check for `window`
**Why**: Fixes issue found with SSR in #204 
**How**: add typeof in the default. Also adds tests to avoid breaking SSR in the future
**Checklist**:
> fix(ssr): add type check for window

- README.md
**What**: Add a multi editable select tags example
**Checklist**:
In case some changes need to be made in the example, please let me know.
I'm not sure if its somehow possible to make the example editable by other people (In case something needs to be fixed / changed in the example in the future).. Or we'll just need to put a different link.
> add editable multi select example

- typings/index.d.ts
**What**: update typing to include onOuterClick
**Why**: it was missing and typescript won't compile if you try to add the onOuterClick prop to the Downshift component
**How**: added typing to include onOuterClick
**Checklist**:
> Add onOuterClick to DownshiftProps typing

- README.md
- src/__tests__/downshift.props.js
- src/downshift.js
#217
Continuation of https://github.com/paypal/downshift/pull/229
**What**:
Provide an onInputValueChange callback to allow to update controlled prop before its old value is used to re-render the children, causing the cursor in the input to jump to the end in the next render.
**Why**:
fixes #217 
**Checklist**:
@kentcdodds I'd like to get your opinion on this change before adding documentation for it.
Do you think this is a direction worth pursuing?
> Fix cursor jumping to end of input

- src/__tests__/downshift.misc.js
- src/downshift.js
**What**:
I'm currently unable to select an item if it's only an empty string.
**Why**:
I'm creating a select input using downshift (which I really enjoy btw, so big props!), and want it to work similar to the native html5 select input. But in downshift I can't select an item if it's an empty string. I could work around it in my implementation, but to me it seems reasonable for downshift to allow the empty string as a value.
Here's a codesandbox for comparison: 
https://codesandbox.io/s/r0kyyx0y1q
**How**:
Only escape from selecting a new item if `item == null`.
**Checklist**:
> fix(selectItemAtIndex): allow selecting empty string

- README.md
relative issue #265
**What**:
Update example 「Integration with Redux」link
**Why**:
relative issue #256
**How**:
Update codesandbox link
**Checklist**:
> Update example 「Integration with Redux」link

- .all-contributorsrc
- README.md
- other/misc-tests/__tests__/preact.js
- package.json
- src/__tests__/downshift.get-button-props.js
- src/__tests__/downshift.get-input-props.js
- src/__tests__/downshift.get-item-props.js
- src/__tests__/downshift.get-label-props.js
- src/__tests__/downshift.get-root-props.js
- src/__tests__/downshift.lifecycle.js
- src/__tests__/downshift.misc.js
- src/__tests__/downshift.props.js
- src/downshift.js
- stories/examples/apollo.js
- stories/examples/axios.js
- stories/examples/basic.js
- stories/examples/controlled.js
- stories/examples/dropdown.js
- stories/examples/multiple.js
- stories/examples/react-autosuggest.js
- stories/examples/react-instantsearch.js
- stories/examples/react-popper.js
- stories/examples/semantic-ui.js
- stories/examples/semi-controlled-list.js
- stories/examples/semi-controlled.js
- stories/examples/windowing-with-react-tiny-virtual-list.js
- stories/examples/windowing-with-react-virtualized.js
**What**: This also moves all examples and tests to use render prop and adds one test to verify the children prop still works
**Why**: Closes #258 
I'm trying to bring some cohesion to the render prop idea.
**How**: the source code change was as simple as `this.props.render ||`. Most of the changes are updating the stories, tests, and docs to use the render prop instead.
**Checklist**:
NOTE: The children prop still works fine. I don't know whether I'll ever drop support for it. Can't think of a reason why I would...
> feat(render): add render prop

- README.md
- src/__tests__/downshift.get-input-props.js
- src/downshift.js
**What**: add `setItemCount` and `unsetItemCount` 
**Why**: This enables developers who need to both asynchronously load options within downshift and window the results. The `itemCount` needs to be set from within downshift so they cannot reasonably use the `prop`.
**How**: Adding a member property to keep track of the set value and a getter (and unsetter as convenience) for that member property.
**Checklist**:
> feat(itemCount): add `setItemCount` and `unsetItemCount`

- src/__tests__/downshift.props.js
- src/downshift.js
**What**: This changes the `reset` functionality to use the `defaultHighlightedIndex` rather than `null`
**Why**: because I think that makes the most sense.
**How**: Simple change and a test addition
**Checklist**:
> fix(reset): respect defaultHighlightedIndex

- .all-contributorsrc
- README.md
- src/__mocks__/utils.js
- src/__tests__/downshift.misc-with-utils-mocked.js
- src/__tests__/downshift.props.js
- src/__tests__/utils.scroll-into-view.js
- src/downshift.js
Fixes #281. 
As I dug into this I realized that it would be nicer to consolidate the code for scrolling to an item so it behaves exactly the same whether or not you are controlling the prop. This will reduce bugs between those use cases.
The way to do this is to always scroll within `componentDidUpdate`. The only problem is that this makes it harder to control scrolling; my first attempt added an option to `setHighlightedIndex` to avoid scrolling, and since that's called directly from `onMouseEvent` we can pass that information. But in `componentDidUpdate` we have no idea why it's changing. However this is always the case in the controlled prop scenario anyway, so we have to accept it.
The only solution is an ugly setTimeout which tells the system to not scroll it at all. This nicely …
> Consolidate scrolling of the list when highlighted index changes and never scroll from a `onMouseEnter` event (fixes #281)

- src/__tests__/downshift.focus-text-input.js
- src/downshift.js
**What**:
Updated querSelector to use escaped selector
**Why**:
Because if my id is "fields[0].name" then focusInput throw an exception
**How**:
easily, I just used my keyboard (and my fingers)
**Checklist**:
> [bug][hotfix] Fix focusInput() by using getElementById

- README.md
**What**:
Updated documentation to show that `onOuterClick` is only fired when `isOpen` is true. (See #311)
**Why**:
This tripped me up a little bit when I was trying to use it.
**Checklist**:
> Added clarification to onOuterClick description

- README.md
- src/__tests__/downshift.props.js
- src/downshift.js
- stories/package.json
**What**:
At now, you could provide your own function that could modify the state that will be set. You could check the type property of stateToSet against this list to know whether you want to modify how the state is changed. [@kentcdodds](https://github.com/kentcdodds)
**Why**:
Chain of ideas: [#319](https://github.com/paypal/downshift/issues/319).
**How**:
```javascript
internalSetState(stateToSet, cb) {
// ...
return this.setState(
state => {
state = this.getState(state)
stateToSet = isStateToSetFunction ? stateToSet(state) : stateToSet
// Your own function that could modify the state that will be set.
stateToSet = this.props.modifyStateChange(stateToSet, state)
// ...
},
// ...
}
```
**Checklist**:
Tests and documentation I can add tomorrow(if nobody else wants).
(modify my wording, …
> Add new prop 'stateReducer'

- README.md
It's not `redux-final-form`
**What**:
The `react-final-form` library was wrongly referenced as `redux-final-form`
**Why**:
Just changed the anchor link to `react-final-form`
**How**:
N/A
**Checklist**:
> Correct `redux-final-form` to `react-final-form`

- src/__tests__/utils.reset-id-counter.js
- src/downshift.js
- src/utils.js
**What**:
This fixes mismatch in client side and SSR generated Id and ensure that Downshift instance is tagged with a single unique id.
**Why**:
Refer to https://github.com/paypal/downshift/issues/340
**How**:
* Set the initial `idCounter` to 0 instead of 1 to match it with `resetIdCounter` call.
* Use `id` to construct all generated ids
**Checklist**:
> fix(generateId): fix initial idCounter and use single unique id for a Downshift instance

- src/downshift.js
**What**: Item click handler does not set `type: Downshift.stateChangeTypes.clickItem`. The bug was introduced from #265.
**Why**: It breaks stateReducer in case `Downshift.stateChangeTypes.clickItem` is being used
**How**: I added back the missing code.
**Checklist**:
> fix: set type Downshift.stateChangeTypes.clickItem on item click

- typings/index.d.ts
**What**:
[Typescript] Fixed the return type for itemToString under Actions interface
**Why**:
Types for itemToString() between DownshiftProps and Actions are not consistent.
**How**:
Changed the return type from `void` to `string`
**Checklist**:
> [Typescript] Fix return type for itemToString under Actions interface

- cypress/integration/basic.js
- cypress/integration/semantic-ui.js
- src/__tests__/downshift.get-button-props.js
- src/__tests__/downshift.get-input-props.js
- src/downshift.js
- stories/examples/semantic-ui.js
**What**: Allow user to tab from input to button without resetting, and allow user to shift+tab from button to input without resetting. See https://github.com/paypal/downshift/issues/364 for more details.
**Why**: If user wanted to only use keyboard to navigate between input and toggle button, the current usage would be a nuisance
**How**: added checks in `input_handleBlur` and `button_handleBlur` to make sure that the new `activeElement` is not a downshift button or downshift input, respectively. Added cypress tests which pass, but I have some work to do regarding keeping and obtaining 100% test coverage
**Checklist**:
Had to add setTimeout in order to prevent the activeElement from being <body>. I looked around and couldn't find any other way to do it. See this link for more info: …
> WIP: test coverage issues with onBlur

- src/downshift.js
**What**: Add a null check for `this._rootNode`
Also refactor so we can read the code
**Why**: Closes #366
**How**:
- Give variable names to things, and use `this._rootNode &&`
**Checklist**:
> fix: add null-check for `this._rootNode`

- src/downshift.js
- src/utils.js
**What**: do not reset when active element is in downshift
**Why**: Closes #356
**How**:
- Add util for checking whether a node is or contains something
- Use that util for both the event.target and the document.activeElement
- Use that instead of the input
**Checklist**:
> fix(mouseup): do not reset when active element is in downshift

- typings/index.d.ts
**What**: Fix for #389
**Why**:
**How**:
**Checklist**:
> [#389] Add missing types for setItemCount and unsetItemCount actions

- src/downshift.js
**What**: IE and certain versions of Edge followed an earlier draft of the DOM spec, and do not include 'Arrow' in their `event.key` events when arrow keys are used (i.e. 'Down' instead of 'ArrowDown', etc). This has been [patched in Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8860571/), but won't be backported to IE. 
**Why**: Preact does not use syntetic events like react does, and as a result arrow keys do not currently work with preact in those browsers.
**How**: check if a keycode is within 37-40 (the range of keyboard arrow keys), and if it does not start with `Arrow`, prepend it to the value.
**Checklist**:
* [ x] Ready to be merged
> Fix keyboard events for IE and Edge in preact

- src/utils.js
**What**: Replaced a string method that works in Edge but not IE11.
**Why**: IE 11 does not support `String.prototype.startsWith`. This method was previously used in #414 and #412 .
**How**: Replaced the String `startsWith` method with `indexOf`
**Checklist**:
> Fix: replace String method not supported in IE11

- package.json
- src/__tests__/downshift.get-item-props.js
- src/downshift.js
At the moment it is possible to select a disabled item by pressing enter although selection by click is disabled. Personally, I think it should not be possible to select a disabled item (at least not for the user).
The event handler checks the DOM-node of the item for the disabled prop.
- fixed faulty behaviour
- updated react-test-renderer
- updated react-testing-library
- added test for fix
> fix: disabled items should not be selectable(#434)

- other/react-native/__tests__/__snapshots__/render-tests.js.snap
- other/react-native/__tests__/onChange-tests.js
- other/react-native/__tests__/render-tests.js
- src/downshift.js
**What**:
This supports both props that <TextInput /> accepts for supporting text
input changed events.
Additionally, this moves onChange related tests to their own module.
**Why**:
Fixes #361 
**How**:
Adds additional argument to `getInputProps` that is only used on React Native builds. This argument is then used to provide an additional event handler.
**Checklist**:
> fix(native): Support both onChange and onChangeText props

- package.json
Currently the `flow-typed` dir is not published.
> Publish flow typings

- typings/index.d.ts
I'm not a TS user, but this was reported and it seems to me that this is easy enough to add it right away
> fix(types): Restored resetIdCounter TS type

- typings/index.d.ts
As per your [`README.md`](https://github.com/paypal/downshift#itemtostring), `itemToString` can be called with a null `Item`. 
> `function(item: any)` | defaults to: `i => (i == null ? '' : String(i))`
This PR fixes your typings to reflect that.
> fix type for itemToString

- src/__tests__/downshift.get-button-props.js
- src/__tests__/downshift.get-input-props.js
- src/__tests__/downshift.lifecycle.js
- src/__tests__/downshift.misc.js
- src/__tests__/downshift.props.js
**What**:
Replace the usage of `dispatchEvent` with `fireEvent` from `react-testing-library`
**Why**:
Being consistent and I can't think of any reason why we need to keep `dispatchEvent`
**How**:
Pretty much just replacing the `dispatchEvent` with the equivalent of `fireEvent`. Bit unsure about bubbling but `react-testing-library` seems to take care of that.
**Checklist**:
> Replace native dispatchEvent with fireEvent from react-testing-library

- src/downshift.js
- src/utils.js
**What**:
Refactor timeout handling when unmounting. Instead of using `_isMounted` we now clear the timeouts.
**Why**:
In my opinion this solution is a more "correct", and probably less error prone way to solve the problem. Now we actually fix the root cause and not the "symptom" (`setState` being called on unmounted components). React has an official [blog post](https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html) about this as well. 
**How**:
I created 2 new instance functions, `internalSetTimeout` and `internalClearTimeouts`. `internaltSetTimeout` is a wrapper around `setTimeout` that pushes the `timeoutId` to an array and removes it when the `setTimeout` callback fires. 
`internalClearTimeouts` loops through all `timeoutIds` and clears them with `clearTimeout`.
Not entirely …
> Refactor timeout handling on unmount

- README.md
**What**: Add link to downshift-examples in the README
**Why**: Because I don't think many people know about these examples and that's where examples should be put.
**How**: Updated the README with a note. Eventually we should entirely replace this section with links directly to modules in that codesandbox, but [that functionality is broken right now](https://github.com/CompuIves/codesandbox-client/issues/989)
**Checklist**:
> docs: add link to downshift-examples

- src/__tests__/portal-support.js
**What**:
Replace deprecated `jest-dom` method
**Why**:
`toBeInDOM` is deprecated
https://github.com/gnapse/jest-dom/issues/34
**How**:
Replace deprecated `toBeInDOM` with `toBeNull` and/or `toBeInstanceOf`
**Checklist**:
> Replace deprecated toBeInDOM method

- src/downshift.js
**This is small output size optimization.**
The only thing needed for `super` here is `props`. So we can just call it with them instead of whole `args`. Because `args` have variadic length the transpiled code has to iterate through `arguments` to create them and we can prevent emitting this `for` loop.
> perf: Call `super` with only props instead of ...args

- README.md
- src/__tests__/__snapshots__/downshift.get-menu-props.js.snap
- src/__tests__/downshift.get-menu-props.js
- src/downshift.js
**What**:
Fixes #490 by using the same approach as we do in `getRootProps`.
**Why**:
Because it could lead to unexpected behavior and to avoid confusion.
**How**:
I'm still unsure of what the best solution for this is. I would like to make the check in the `render` method as we do for the `getRootProps`, but I don't think that's possible because the ref hasn't set `this._menuNode` on the first render. I guess we could loop through all children but that seems unnecessary heavy/slow.
So instead I make the validation/check in `componentDidUpdate`, which looks to work fine.
Another problem I encountered was that there is no way to check if `this._menuNode` is a composite element or not, which makes it hard to use the same validation as we do for `getRootProps`.
I wanted you opinion on this …
> Validate that getMenuProps has set the ref correctly

- README.md
Fixes #490 
**What**:
Documentation improvements.
**Why**:
We should explicitly call out that menus should be mounted all the time, regardless of whether it's hidden or not.
**How**:
Updated the documentation to reflect this.
**Checklist**:
> Updated documentation regarding getMenuProps

- .size-snapshot.json
- README.md
- src/__tests__/downshift.lifecycle.js
- src/downshift.js
**What**: feat(scrollIntoView): add new prop to override built-in scrollIntoView
**Why**: Closes #537
**How**: React makes this easy. I leverage `defaultProps` to set our own implementation of `scrollIntoView` as the `scrollIntoView` prop and then call it via `this.props.scrollIntoView` so users of downshift can override it to be whatever they want.
This means that I had to change the test slightly because the `scrollIntoView` function is no longer called directly on `utils` so we can't spy on it. Just swapped that to use mocking and it's working fine.
**Checklist**:
> feat(scrollIntoView): add new prop to override built-in scrollIntoView

- .size-snapshot.json
This commit is also a part of #542 , would be good to merge this separately so other PRs can be rebase etc against master with latest size snapshot.
> chore: update size snapshot

- .npmrc
- .size-snapshot.json
- package.json
- src/downshift.js
- src/is.macro.js
- src/utils.js
fixes #540
Some snapshot sizes are bigger, some are smaller. This PR should remove some bytes in all the cases, gonna investigate this in a moment - I suspect those differences might be caused by newer versions of downshift's deps and not downshift itself, but cant be sure right now.
EDIT:// yeah, running the build on master with fresh deps updates the snapshot, so size regressions are not caused by this PR
@TrySound would it be possible to output additional snapshot sizes for the lib itself with all deps as external? Both numbers are valuable (with externals bundled in and without them)
> chore: inline build variables with custom simple macro

- typings/index.d.ts
**What**
The DownshiftProps typescript type does not include the following props: inputId, labelId, menuId, getItemId.  See issue #530 .  This PR adds the missing props.
**Why**
To improve typescript support
**Checklist**:
After running `npm run setup`, but before making any changes to the repo, I noticed the .size-snapshot.json was changed.  The changes in this PR didn't affect the .size-snapshot.json file that is generated, so I didn't commit `.size-snapshot.json`.   Please let me know if you would like me to.
> add id props to DownshiftProps type

- typings/index.d.ts
Fixes the typing part of #490
**Why**: The typings for `getMenuProps` was too broad.
**How**:
Created interfaces for the types of parameters of `getMenuProps`
**Checklist**:
> Improved typings for getMenuProps

- .size-snapshot.json
- other/misc-tests/jest.config.js
- package.json
**Motivation**
https://github.com/kentcdodds/kcd-scripts/pull/71
> chore(tooling): update kcd-scripts

- README.md
**What**: The goal is to fix #620.
**Why**: The documentation does not list the possible values for the `type` property.
**How**: Added missing documentation.
**Checklist**:
> Document stateChangeTypes in README.md

- src/__tests__/downshift.get-button-props.js
- src/__tests__/downshift.get-input-props.js
- src/downshift.js
**What**: Stop the propagation of keydown events that have been handled by downshift
**Why**: If I am using downshift inside a component that is also handling key events then it shouldn't be receiving them if downshift has already taken action
**How**: using `event.stopPropagation()`
**Checklist**:
This fixes issue #630
> Stop handled key events propagating

- .size-snapshot.json
- README.md
- src/__tests__/downshift.lifecycle.js
- src/downshift.js
- src/utils.js
**What**: Use `menuNode` instead of `rootNode` as scrolling boundary.
**Why**: Closes #638
**How**: By changing the `scrollIntoView` callsite and updating docs and tests to refer to `menuNode`.
**Checklist**:
Somehow this change gzips better and reduces bundlesize by a whopping *1 byte* 🎉 
Looks like my VS Code reorganized the imports ordering, I didn't intend to do that but I guess it doesn't hurt anyone 😅
> fix(scrollIntoView): use menuNode for boundary

- .size-snapshot.json
- cypress/integration/combobox.js
- src/__tests__/downshift.get-input-props.js
- src/downshift.js
- src/stateChangeTypes.js
**What**:
This PR aims to improve kb navigation inside the listbox by adding support for `Home` and `End`. These keys should highlight first / last element, if the listbox is visible.
**Why**:
Improves the component by adding another ARIA specification regarding kb navigation.
**How**:
Added event listeners for keydown on both `Home` and `End`, and added handlers for each, in which I've used variations for the `setHighlightedIndex` function. Also added event names for both kets.
Also added UTs for these changes, and planning to add E2E Cypress tests too. These are already written, however Cypress does not support Home and End at the moment. I've created a PR for implementing this in their repo [here](https://github.com/cypress-io/cypress/pull/3071). Those tests are currently commented. …
> Handle End and Home Keys in list navigation

- src/__tests__/downshift.get-button-props.js
- src/__tests__/downshift.get-input-props.js
- src/downshift.js
This reverts commit 5084cd05d0ca5ef7ff9f95de5a8dab9e882d73d8.
**What** and **Why**
The changes as part of #633 were incomplete, did not provide a way to allow downshift to handle event and optionally stop propagation, and incorrectly always stopped event propagation on Escape Keydown events.
See discussion in #642 and #643
Whilst we may want to do some stopping of propagation, for now this just reverts that PR so that the events are always propagated.
> Revert "fix(events): stop handled key events propagating (#633)"

- src/downshift.js
**What**:
Fixes: 
> Unable to get property 'dataset' of undefined or null reference
errors on IE11.
**Why**:
We're using downshift on our webpage that (unfortunately) still needs to support IE11. We noticed bunch of errors in our error tracking pointing to downshift.
**How**:
I added additional guard clause to `inputHandleBlur` that verifies that `activeElement` on which `dataset` is called actually exists.
**Checklist**:
> fix(ie11): added extra guard condition for ie11 issue

- src/__tests__/downshift.get-input-props.js
- src/downshift.js
- src/utils.js
**What**:
Fixes item highlights in the case of passing `highlightedIndex`, `defaultHighlightedIndex` and `initialHighlightedIndex`. Handles both toggle and opening by keyDown and keyUp. Also has some code refactoring + unit tests for `getInputProps`. Planning to also add unit tests for `getToggleButtonProps`.
> fixed index highlights in toggle and keydown

- other/manual-releases.md
There was an issue with a patch release, so this manual-releases.md
change is to release a new patch version.
Reference: #674
> fix(release): manually release a patch version

- .size-snapshot.json
- src/downshift.js
PR for removing the call to reset in toggleMenu introduced by https://github.com/downshift-js/downshift/pull/674. Will just reset the `highlightedIndex` to `defaultHighlightedIndex` on toggle.
Selecting the highlighted index is something we want to improve. https://github.com/downshift-js/downshift/issues/679
> fix(toggleMenu): removed breaking reset

- .size-snapshot.json
- src/__tests__/downshift.get-button-props.js
- src/downshift.js
I really hope this is the final version for this area. Previously I used `toggleMenu` when opening by arrow keys but that implied two calls for `setHighlightedIndex` which was not necessary.
> fix(keyDownHandlers): call setState instead of toggle when opening

- src/downshift.js
`shouldScroll` was using `this.state` and it wasn't taking into account the controlled `highlightedIndex` prop. replaced with the proper call,` this.getState()`.
> fix(scroll): added getState call instead of state

- src/__tests__/downshift.get-input-props.js
- src/__tests__/downshift.misc-with-utils-mocked.js
Fixes: 
`[lint]   47:26  error  Prefer toHaveBeenCalledWith(/* expected args */)  jest/prefer-called-with`
> fix(lint): change jest method that is breaking the build

- src/__tests__/__snapshots__/set-a11y-status.js.snap
- src/__tests__/set-a11y-status.js
- src/set-a11y-status.js
**What**:
Stops appending status messages and performs cleanup after setting them.
**Why**:
Screen reader will not re-narrate if we use this trick. Tried it also in the JQuery https://jqueryui.com/autocomplete/ implementation and if you append two or more statuses that are the same, one after another, they will not be re-narrated.
Cleans up after a timeout so that when users use Virtual Cursor from screen readers they will not bump into this status message, which would be confusing for them.
**How**:
Refactored the `setStatus` function to append text on top of the existing one. Also created a setTimeout for cleanup. If there will be a text overlapping over existing one, the clean up callback from the previous will be cleared.
**Checklist**:
> fix(set-a11y-status): perform cleanup after setting a status

- README.md
Closes #719
**What**:
Update docs to mention onChange can be called with null when selection is cleared.
**Why**:
As discussed in #719, version 3.2.10 changed the behavior of the escape key to clear the selection and call onChange with null. This updates the docs to make that clear.
**Checklist**:
PR in downshift-examples already merged: https://github.com/kentcdodds/downshift-examples/pull/15
I think we'll also want to update the [Try it out in the browser](https://codesandbox.io/s/6z67jvklw3) link in the README, but I'm not sure how to go about updating it.
> Update docs to mention onChange can be called with null

- README.md
Follow up on https://github.com/downshift-js/downshift/pull/721.
Forked the previous example from codesandbox, applied the new way to use `onChange`, and used that as the link from 'Try it yourself'.
@TLadd is it working now?
> docs(usage): change the usage codesandbox link

- src/downshift.js
**What**:
Fixes environment being `undefined` on `this.props` on cleanup
**Why**:
Closes #725
**How**:
Destructure `environment` from `this.props` before cleanup so we have access to it in the cleanup. This is one reason why hooks are awesome. Because they do this by default.
**Checklist**:
> fix: environment undefined in props on cleanup

- .size-snapshot.json
- package.json
Does not provide any value to Downshift since we are generating that by `getLabelProps`. And it breaks all our examples and builds.
> fix: disable lint label a11y rule

- typings/index.d.ts
**What**:
Added a type definition for the `scrollIntoView` prop.
**Why**:
While the docs describe the type signature of `scrollIntoView`, not having it in the typings file makes TypeScript fail when using this prop.
**How**:
Added a new key with type definitions to the `DownshiftProps` definition in `typings`
**Checklist**:
Also, big thanks to everyone that maintains this library, using downshift has  made my life a _ton_ easier so very happy to give back a little 😎
> Add type definitions for scrollIntoView prop

- src/set-a11y-status.js
Using `debounce()` to cleanup a11y status message.
> chore(set-a11y-status): use debounce for a11y message cleanup

- .size-snapshot.json
- src/downshift.js
- src/set-a11y-status.js
Downshift already supports getting `environment` as prop and uses it throughout the component. It should also be passed to set-a11y-status `setStatus` so that it will be used to create the status div in the correct `document`.
> fix(set-a11y-status): pass props.environment.document to getStatusDiv

- .size-snapshot.json
- rollup.config.js
- src/hooks/useSelect/__tests__/getItemProps.test.js
- src/hooks/useSelect/__tests__/getMenuProps.test.js
- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/__tests__/props.test.js
- src/hooks/useSelect/index.js
- src/hooks/useSelect/utils.js
- src/hooks/utils.js
replaced `import * as X` with `import X from`. Also reverted added rollup named exports added by https://github.com/downshift-js/downshift/pull/747
> fix(rollup): imports and revert added namedExports

- typings/index.d.ts
**What**:
Fixes #763
**Why**:
#763
**How**:
Made everything except items in UseSelectProps optional and made useSelect accept UseSelectProps instead of UseSelectInterface
**Checklist**:
`npm run add-contributor` prints following:
```
> downshift@0.0.0-semantically-released add-contributor <downshift>
> kcd-scripts contributors add
<downshift>/node_modules/kcd-scripts/dist/run-script.js:49
throw new Error(`Unknown script "${script}".`);
^
Error: Unknown script "contributors".
at spawnScript (<downshift>/node_modules/kcd-scripts/dist/run-script.js:49:11)
at Object.<anonymous> (<downshift>/node_modules/kcd-scripts/dist/run-script.js:12:3)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load …
```
> fix(TS): correct TypeScript typings for useSelect

- .size-snapshot.json
- package.json
- src/hooks/useSelect/__tests__/getItemProps.test.js
- src/hooks/useSelect/__tests__/getMenuProps.test.js
- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/__tests__/props.test.js
- src/hooks/useSelect/index.js
Added as part of 3.3.0 but will remove it to shave the bundle size a bit.
> perf: remove keyboardKey library and replace its uses

- .all-contributorsrc
- .size-snapshot.json
- src/hooks/useSelect/index.js
**What**:
Localize clearTimeout per useSelect mounted instances
**Why**:
Closes #794 
Previously, clearTimeout was previously at root level closure, causing each new mounted component that used the useSelect hook to override the previous reference, so every instance of the component was alway calling only the last instance's clearTimeout, never calling their own clearTimeout and therefore, never clearing the `keysSoFar` state. 
**How**:
Assigned resulting clearTimeout to a ref, instead of the root closure variable
**Checklist**:
> fix - Localize clearTimeout per useSelect mounted instances

- src/hooks/useSelect/README.md
- src/hooks/useSelect/__tests__/getMenuProps.test.js
- src/hooks/useSelect/index.js
- src/hooks/useSelect/reducer.js
- src/hooks/useSelect/stateChangeTypes.js
- typings/index.d.ts
Should fix https://github.com/downshift-js/downshift/issues/780
Will reset `highlightedIndex` on mouse leave from menu.
Will not select item on Tab, Shift Tab, and mouse click outside.
ToDo:
- Update Documentation.
> fix(useSelect): don't select item at blur

- .size-snapshot.json
- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/index.js
**What**: bug
**Why**: [documentation](https://github.com/downshift-js/downshift/tree/master/src/hooks/useSelect#gettogglebuttonprops) states `getToggleButtonProps` accepts `disabled` option, but actually it doesn't
**Checklist**:
> fix(useSelect): respect disabled option passed to `getToggleButtonProps`

- .size-snapshot.json
- src/hooks/useSelect/__tests__/getItemProps.test.js
- src/hooks/useSelect/index.js
**What**:
`disabled` property is ignored when passed to `getItemProps`
**Why**:
Not respecting `disabled` property causes unwanted handlers to trigger on hover and click (opposite to the what [docs](https://github.com/downshift-js/downshift/tree/master/src/hooks/useSelect#getitemprops) says)
**How**:
I followed the convention that @maxmalov used to fix similar bug (#829), but in `getToggleButtonProps`. 
**Checklist**:
> fix(useSelect): respect disabled option passed to `getItemProps`

- .size-snapshot.json
- package.json
- src/downshift.js
The main reason for doing this is because we are calling `getItemProps` to apply attributes / handlers and also to supply Downshift with items. If we want to avoid calling it so that we don't re-render the item, Downshift on re-render will throw away the items references and will not know about them anymore.
Since there is no way to avoid calling this with current `Downshift` implementation, we should at least provide the event handlers as memoized functions, so if your item is a pure component and it does not have to change, it will not.
Probably we should use this approach with the rest of the handlers as well, will need to look into it soon.
> perf(getItemProps): memoize the event handlers for item

- .size-snapshot.json
- package.json
- src/downshift.js
This reverts commit c90e41b9cdce8be4f04fde3b46ae775d2cd915b7.
As discussed here https://github.com/downshift-js/downshift/issues/845
Will look for an alternative approach to this as we should still avoid re-rendering of items if not needed. Having 200+ React components will cause slow experience, and if those components are pure and we don't create new handlers every time, re-rendering should be avoided.
To be updated in the future.
> fix(revert): Revert "perf(getItemProps): memoize the event handlers for item (#841)"

- .size-snapshot.json
- typings/index.d.ts
Bundling https://github.com/downshift-js/downshift/pull/839/ and https://github.com/downshift-js/downshift/pull/840/ together. Fixes https://github.com/downshift-js/downshift/issues/836 and https://github.com/downshift-js/downshift/issues/838.
Many thanks to @saitonakamura for these fixes! @all-contributors please add @saitonakamura for bug and code!
> fix(ts): fix useSelect typings for stateReducer and stateChangeTypes

- .babelrc.js
- .size-snapshot.json
- package.json
- rollup.config.js
- src/hooks/useSelect/index.js
`defaultProps` and `stateChangeTypes` prevent Downshift from being tree-shakeable. Also the prop type checks in `useSelect`.
Use `no-side-effect-class-properties` in `.babelrc.js` along with the original configs from `kcd-scripts`. https://github.com/naver/babel-plugin-no-side-effect-class-properties @kentcdodds maybe you want to include this as well or mark it to be added once a more official version is released.
Updated `rollup.config.js` to use the babel config file.
Only check hook prop-types if not on production.
Result: treeshakeable Downshift.
Most grateful to @layershifter for contributing with this.
https://github.com/babel/babel/issues/8592
https://github.com/babel/babel/pull/6963
> fix: treeshake Downshift and useSelect

- test/basic.test.tsx
- typings/index.d.ts
This simplifies TypeScript typings and allows to use `Downshift` instance with generic parameter.
It's possibly a breaking change, because I've removed `DownshiftInterface` as it's no longer needed.
Fixes #693 
**Checklist**:
> Simplify TS typings

- other/manual-releases.md
There was an issue with a major release, so this manual-releases.md
change is to release a new major version.
Reference: https://github.com/downshift-js/downshift/pull/860
BREAKING CHANGE: TypeScript typings have changed for both `useSelect` and `Downshift`. See PR for details.
> fix(release): manually release a major version

- src/hooks/README.md
**What**:
README link for useCombobox incorrectly linked to useSelect README; should have been the useSelect README
**Why**:
Issue makes docs harder to read.
**How**:
Simple text change
**Checklist**:
> docs: fix incorrect link to useCombobox

- README.md
- docs/downshift/downshift.mdx
- docs/index.mdx
- doczrc.js
**What**:
Fixes https://github.com/downshift-js/downshift/issues/779.
**Why**:
The main `Downshift` use example is not accessible with screen readers. The HTML structure for a `combobox` is not achievable without using getRootProps.
**How**:
Change main Downshift usage example. Added more information on why is it important to use that instead of the previous one. Also added a docs page for both these usages.
**Checklist**:
> docs: combobox HTML correct structure in documentation

- .size-snapshot.json
- src/hooks/useSelect/README.md
- src/hooks/useSelect/__tests__/getMenuProps.test.js
- src/hooks/useSelect/index.js
- src/hooks/useSelect/reducer.js
- src/hooks/useSelect/stateChangeTypes.js
- typings/index.d.ts
**What**:
Making the menu on `useSelect` behave the same way when pressing spacebar or enter.
**Why**:
`<select>` also behave like that. See https://github.com/downshift-js/downshift/issues/853 for more detail.
**How**:
- Add a new `stateChangeTypes`, `MenuKeyDownSpaceButton`
- Dispatch it when receiving `' '` key on menu
- Handle that action in the reducer the same way `MenuKeyDownEnter` is handling.
**Checklist**:
> fix(useSelect): add support for space button on menu

- src/hooks/useCombobox/README.md
**What**:
Fix small typo on the Combobox's README
> docs: fix typo in useCombobox README

- typings/index.d.ts
**What**:
Changed `getInputProps` and `getComboboxProps` options parameter to be optional in `useCombobox` hook.
**Why**:
They are not required, if I understand it correctly. You can see it in the [Usage documentation](https://github.com/downshift-js/downshift/tree/c9479dc4f508a1a4fd298f69c8f5cdeefa3d4b6f/src/hooks/useCombobox#usage). Also, they are out of sync with `Downshift` component. Only `getItemProps` requires options to pass `item`.
**How**:
**Checklist**:
> fix(typings): optional options for `getInputProps` and `getComboboxProps`

- .size-snapshot.json
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/__tests__/getItemProps.test.js
- src/hooks/useCombobox/__tests__/getToggleButtonProps.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useSelect/__tests__/getItemProps.test.js
- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
**What**:
Currently, `getToggleButtonProps` & `getItemProps` accept a `disabled` prop to remove handlers but won't pass that prop down.
**Why**:
Allows components to be styled dependent on the `disabled` prop. Accessibility?
**How**:
Simply pass down the `disabled` prop.
**Checklist**:
Added tests for both `useSelect` and `useCombobox`.
> fix(useCombobox): pass down missing disabled prop in prop getters

- src/hooks/useCombobox/__tests__/getComboboxProps.test.js
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/__tests__/getMenuProps.test.js
- src/hooks/useCombobox/__tests__/getToggleButtonProps.test.js
- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useSelect/__tests__/getMenuProps.test.js
- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/__tests__/props.test.js
Using `act` either from testing-library/react or react-hooks.
> chore(hooks): improve use of react act in tests

- docs/hooks/useCombobox.mdx
Changes the codesandbox link of the `useCombobox` example with `stateReducer`.
> docs(useCombobox): change stateReducer codesandbox link

- .size-snapshot.json
- typings/index.d.ts
**What**:
`UseSelectPropGetters` interface has some wrong types used. This PR fixes the issue.
**Checklist**:
> fix(useSelect): correct typings for toggleButton and menu getter props

- .size-snapshot.json
- src/downshift.js
- src/hooks/utils.js
- src/utils.js
In the hooks, the function was checking initially if the prop is undefined, then it was changed to `prop in props` in 3.3.2. Since in Downshift it's checking for undefined as it was initially in the hooks, I moved the function in the utils so it can be used for both the hooks and the component. Behaviour should be unified now.
> fix(getState): revert the controlled prop check

- README.md
Fixes #870 
I just removed the `prop-types` citation from the `README`, nothing to test here.
> removing prop-types from README

- docs/hooks/useCombobox.mdx
It is pointing to `useSelect` markdown file
> ✏️ Fix wrong github page link

- .size-snapshot.json
- src/hooks/utils.js
After the discussion at https://github.com/downshift-js/downshift/issues/927.
Should re-open https://github.com/downshift-js/downshift/issues/874 and fix it in another way.
Closes https://github.com/downshift-js/downshift/issues/927.
> fix: revert 4.0.8 and 4.0.9 changes

- .size-snapshot.json
- src/hooks/useCombobox/__tests__/getItemProps.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useSelect/__tests__/getItemProps.test.js
- src/hooks/useSelect/index.js
This should ensure compliance with ARIA and consistency with `<Downshift>`.
Fixes https://github.com/downshift-js/downshift/issues/928.
> feat(hooks): add aria-selected="false" to each non-highlighted item

- .travis.yml
Otherwise semantic-release would not release.
Updating node_js version in travis.yml from 8 to 10.
> chore: update node version in .travis.yml

- .size-snapshot.json
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useSelect/__tests__/getMenuProps.test.js
- src/hooks/useSelect/index.js
Based on https://github.com/downshift-js/downshift/pull/926, means to fix the issue where in hooks we can have `aria-activedescendant` with a item value even though the menu is closed and the item does not exist.
Fixes https://github.com/downshift-js/downshift/issues/921.
> fix(hooks): only add aria-activedescendant when menu is open

- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useSelect/__tests__/props.test.js
- src/hooks/utils.js
**What**:
Fixes https://github.com/downshift-js/downshift/issues/963.
Should call onStateChange with a type now, and also only with props that changed.
**Why**:
Previous implementation was not following the API.
**How**:
Filtered the changes that we call onStateChange with.
**Checklist**:
> fix(hooks): call onStateChange with type and only changed props

- src/hooks/utils.js
Object.entries is not required because the value in the object is not being used. Replaced with Object.keys as at least it is supported on IE 9 and later.
See https://github.com/downshift-js/downshift/issues/970
> fix(hooks): replace Object.entries with Object.keys to support > IE 9

- typings/index.d.ts
**What**:
Added missing `scrollIntoView` type definitions for `useSelect` and `useCombobox` hooks.
**Why**:
Was getting Typescript error while trying to pass `scrollIntoView` prop to `useCombobox`:
```
Object literal may only specify known properties, and 'scrollIntoView' does not exist in type 'UseComboboxProps<string>'
```
**How**:
A small edit to the `typings/index.d.ts` file
**Checklist**:
> fix(typescript): add missing `scrollIntoView` definitions to hooks

- src/hooks/useCombobox/README.md
**What**:
The `useCombobox` readme refers to `useCombobox.stateChangeTypes.MenuKeyDownEnter`, which doesn't exist.
**Why**:
Makes it possible to follow the docs without digging into the code to find the type.
**Checklist**:
> docs(useCombobox): fix stateReducer example to use correct stateChangeType

- README.md
- docs/tests/combobox.js
- flow-typed/npm/downshift_v2.x.x.js.flow
- other/react-native/__tests__/onBlur-tests.js
- other/react-native/__tests__/onChange-tests.js
- other/react-native/__tests__/render-tests.js
- other/ssr/__tests__/index.js
- src/__tests__/downshift.aria.js
- src/__tests__/downshift.focus-restoration.js
- src/__tests__/downshift.get-button-props.js
- src/__tests__/downshift.get-input-props.js
- src/__tests__/downshift.get-item-props.js
- src/__tests__/downshift.get-label-props.js
- src/__tests__/downshift.get-menu-props.js
- src/__tests__/downshift.get-root-props.js
- src/__tests__/downshift.lifecycle.js
- src/__tests__/downshift.misc-with-utils-mocked.js
- src/__tests__/downshift.misc.js
- src/__tests__/downshift.props.js
- src/__tests__/portal-support.js
- src/__tests__/utils.reset-id-counter.js
- src/hooks/useCombobox/README.md
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/testUtils.js
- src/hooks/useSelect/README.md
- src/hooks/useSelect/__tests__/getMenuProps.test.js
- src/hooks/useSelect/testUtils.js
- test/basic.test.js
**What**:
Migrated to `import * as React from 'react'`
**Why**:
Ref https://github.com/facebook/react/pull/18102
This is the recommended way to import react now.
**How**:
With the help of replace-in-files-cli package
**Checklist**:
> Migrate to import * as React from 'react'

- src/__tests__/downshift.get-input-props.js
- src/downshift.js
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/index.js
**What**:
Recreating the fix from https://github.com/downshift-js/downshift/pull/671.
**Why**:
Handle this case by default in Downshift without users having to create boiler plate handling.
Handle IME composing events.
**How**:
Check for `event.which === 229`. If true, then will wait for a subsequent event without composing.
More info on:
https://github.com/mui-org/material-ui/issues/19435
https://github.com/zendeskgarden/react-components/issues/598
**Checklist**:
> fix(input): handle IME events on input Enter keydown

- README.md
- src/hooks/useCombobox/README.md
- src/hooks/useSelect/README.md
This commit includes one small, overall style change, as well: [most U.S. style guides recommend that "e.g." be followed by a comma][0], whereas the downshift docs leave it bare.
The core changes in this commit use the phrase "e.g." in a few places, so in the interest of consistency, this commit applies the comma both in new additions and existing instances of "e.g." throughout the docs.
[0]: https://www.dailywritingtips.com/comma-after-i-e-and-e-g/
1. I did not run pre-commit hooks because `kcd-scripts test --findRelatedTests` just hung forever. Let me know if I need to make this work.
2. I removed the following point in the `useCombobox` docs:
> It is also used to allow highlighting by typing character keys, when downshift looks for the items whose string version start with the keys …
> docs: Add null-check note for itemToString (#975)

- .size-snapshot.json
- docs/hooks/useCombobox.mdx
- docs/hooks/useSelect.mdx
- package.json
- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useCombobox/reducer.js
- src/hooks/useCombobox/stateChangeTypes.js
- src/hooks/useCombobox/testUtils.js
- src/hooks/useCombobox/utils.js
- src/hooks/useMultipleSelection/index.js
- src/hooks/useSelect/index.js
- src/hooks/utils.js
- typings/index.d.ts
**What**:
Improving the state management by using a useState approach rather than a useReducer one. Also adding a new state transition similar to the one in `Downshift` which updates `inputValue` if the `selectedItem` is controlled via prop and it gets updated.
**Why**:
We had the issue with the reducer that it wasn't a pure function, as we called the onChange handlers inside the callback passed to `useReducer`. This throws a warning in newer versions of React.
We also had the issue of `inputValue` not refreshing properly when a controlled `selectedItem` via props changed its value.
**How**:
`inputValue` refresh is done in a similar way how it's done in the `Downshift` component.
`useEnhancedReducer` has been replaced with `useControlledState` in which we call onChange handlers from …
> fix(hooks): replace useReducer with useState

- src/hooks/useSelect/__tests__/props.test.js
- src/hooks/useSelect/index.js
**What**:
MenuBlur state change was triggered after item selection (ItemClick, MenuEnter or MenuSpaceButton).
**Why**:
This state change was not needed and it was confusing. Blur change should be triggered only on (Shift)Tab and outside click.
**How**:
With a ref value. When we blur the menu by programatically focusing the triggerButton, after item selection, we will make that value `false`. This way, when the handler for the menu blur is triggered, it checks this value, and if it's false, it sets it back to true and returns, without triggering the blur action.
**Checklist**:
Fixes https://github.com/downshift-js/downshift/issues/965.
> fix(useSelect): don't trigger blur state change after item selection

- .size-snapshot.json
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useCombobox/testUtils.js
**What**:
Ref https://github.com/downshift-js/downshift/issues/1019
**How**:
Allow to submit form on pressing Enter when menu is closed or
no item is selected.
**Checklist**:
> fix(useCombobox): allow to submit form on pressing Enter

- .size-snapshot.json
- src/hooks/useCombobox/index.js
- src/hooks/useSelect/index.js
- src/hooks/utils.js
- src/utils.js
**What**:
Moves the tracker for mouse and touch events to a separate hook and call it only when isOpen changes.
**Why**:
Avoid duplication and prevent it from running at every render.
**How**:
Moved the whole `useEffect` and the refs for the touch and mouse events to a separate hook. Calling that hook from useCombobox and useSelect, so no more duplication.
There is also no need to call this effect unless the isOpen or environment change.
Can probably be further improved. Ideally it should be re-called when any variable in useEffect changes. Will happily accept further improvements here.
**Checklist**:
Closes https://github.com/downshift-js/downshift/issues/1031
> perf(hooks): improve mouse and touch tracking

- .size-snapshot.json
- cypress/integration/useSelect.js
- docs/tests/index.mdx
- docs/tests/useSelect.js
- docs/tests/useSelect.mdx
- src/hooks/useCombobox/index.js
- src/hooks/useSelect/index.js
- src/hooks/utils.js
**What**:
Return the container object from `useMouseAndTouchTracker`.
**Why**:
To return the updated result properly between re-renders.
**How**:
Return the ref with the object that is getting updated by the mouse and touch handlers we are setting in `useMouseAndTouchTracker`.
**Checklist**:
Fixes https://github.com/downshift-js/downshift/issues/1037.
> fix(hooks): return the ref container with isMouseDown

- docs/hooks/useSelect.mdx
**What**:
Showcase the Windows-specific behavior of a select on ArrowUp/ArrowDown with menu closed.
Instead of opening the menu with a highlightedIndex, we just select the previous/next item.
**Why**:
Better use case to illustrate.
**How**:
Change the stateReducer.
**Checklist**:
Closes https://github.com/downshift-js/downshift/issues/792.
> docs(useSelect): change the docsite stateReducer example

- src/__tests__/downshift.get-menu-props.js
**What**: Adding test to show how a `ref` can be passed as a function to `getMenuProps`. 
**Why**: Docs are not clear about this feature. This is particularly useful when you need access to the menu element for positioning purposes using `getBoundingClientRect`.
**How**: Change exists already -- just adding a test to highlight the feature.
**Checklist**: Maybe?
> Adding tests supporting function refs

- src/__mocks__/utils.js
- src/__tests__/downshift.lifecycle.js
- src/hooks/useCombobox/__tests__/memo.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useCombobox/testUtils.js
- src/hooks/useMultipleSelection/__tests__/memo.test.js
- src/hooks/useMultipleSelection/index.js
- src/hooks/useMultipleSelection/testUtils.js
- src/hooks/useSelect/__tests__/memo.test.js
- src/hooks/useSelect/index.js
- src/hooks/useSelect/testUtils.js
- src/hooks/utils.js
**What**:
This PR memoizes all callbacks returned from downshift so we can memoize function components and pass callbacks in dependency arrays.
**Why**: Closes #1050
**How**:
This was a bit tricky, but basically the way we made this work properly to avoid the issues brought up in #1050 is by making a `latest` ref which contains the latest version of `props` and `state` and then we could reference that in our memoized callbacks without having memoization broken whenever those values changed because our callbacks all only care about the latest values anyway (this is the way the class-based downshift works as well).
Had to memoize the `dispatch` function as well. Minimal impact there.
**Checklist**:
> feat(hooks): memoize all callbacks

- .size-snapshot.json
- src/downshift.js
- src/hooks/useCombobox/README.md
- src/hooks/useCombobox/__tests__/getComboboxProps.test.js
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/__tests__/getMenuProps.test.js
- src/hooks/useCombobox/__tests__/getToggleButtonProps.test.js
- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useCombobox/testUtils.js
- src/hooks/useMultipleSelection/README.md
- src/hooks/useMultipleSelection/__tests__/getDropdownProps.test.js
- src/hooks/useMultipleSelection/__tests__/props.test.js
- src/hooks/useMultipleSelection/index.js
- src/hooks/useMultipleSelection/testUtils.js
- src/hooks/useSelect/README.md
- src/hooks/useSelect/__tests__/getMenuProps.test.js
- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/__tests__/props.test.js
- src/hooks/useSelect/index.js
- src/hooks/useSelect/testUtils.js
- src/hooks/utils.js
- src/utils.js
**What**:
Adding non-production build errors in the hooks similar to the ones in Downshift: for controlled-uncontrolled props switch and also for incorrect call of getter props.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1024.
Fixes https://github.com/downshift-js/downshift/issues/974.
**How**:
Keep a ref with previous props and check with current props if there was a switch between controlled and uncontrolled state.
Keep a ref to keep information about whether the getter props were called and if were called correctly (ref was correctly set).
If issues are found, we console.error messages in non-production environments.
**Checklist**:
> chore(hooks): add controlled props and getter props warnings

- src/utils.js
**What**: fix(scrollIntoView): do not scroll falsy node
**Why**: Ref: https://github.com/downshift-js/downshift/pull/1045#issuecomment-628682162
**How**: swap `if (node === null) return` with `if (!node) return`
**Checklist**:
> fix(scrollIntoView): do not scroll falsy node

- src/hooks/useCombobox/__tests__/returnProps.test.js
- src/hooks/useCombobox/reducer.js
**What**:
When using action prop `selectItem` we should also update the `inputValue` to be its string 
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1049.
**How**:
Fix the state change in the reducer to also return the inputValue.
**Checklist**:
> fix(useCombobox): update inputValue when calling selectItem

- docs/index.mdx
The docs page has a broken link because it has an ending parenthesis ")" at the end.
**What**:
This removes a parenthesis character that causes a broken link
**Why**:
The link does not work without this change.
**How**:
**Checklist**:
Free to do more work to merge this if needed
> Fix link on docs page

- docs/hooks/useMultipleSelection.mdx
- docs/utils.js
- src/hooks/useMultipleSelection/README.md
Correct a typo in use multiple select documentation page.
**What**:
We want to keep documentation clear without any typos.
**Why**:
Changed the style name from `menuMultipleStlyes` to `menuMultipleStyles` in all possible places.
**How**:
**Checklist**:
> docs(hooks): changed name of a style in use multiple combobox example

- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/__tests__/getItemProps.test.js
**What**:
Use `toHaveValue` from the jest dom extended expect
**Why**:
Make tests easier tor read and understand.
**How**:
Replace `expect(input.value).toEqual` with `expect(input).toHaveValue`.
**Checklist**:
> chore(tests): use expect.toHaveValue in tests

- cypress/integration/useCombobox.js
- docs/tests/useCombobox.js
- docs/tests/useCombobox.mdx
- src/hooks/useCombobox/index.js
**What**:
Focus the `input` after item click
**Why**:
To have consistency with Downshift behavior and other libraries.
Fixes https://github.com/downshift-js/downshift/issues/1014.
**How**:
Use `inputRef.current.focus` after the dispatch.
**Checklist**:
> fix(useCombobox): focus input after selection by click

- src/hooks/useCombobox/README.md
**What**:
Change in the Readme the default value for `circularNavigation` from `false` to `true` in order to correctly document the prop.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1084.
**How**:
Readme change.
**Checklist**:
> docs(useCombobox): fix the default value for circularNavigation

- docs/hooks/useCombobox.mdx
- docs/hooks/useMultipleSelection.mdx
- docs/hooks/useSelect.mdx
- package.json
**What**:
Have playgrounds for all examples and have links at the bottom of the docsite.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1081.
**How**:
Add sandboxes linked to the playgrounds, for each example, and move all links to the end of the page.
**Checklist**:
> docs(hooks): improve playgrounds and links

- docs/hooks/useCombobox.mdx
- docs/hooks/useSelect.mdx
- package.json
**What**:
Add examples of using useSelect and useCombobox with useVirtual from react-virtual.
**Why**:
Provide usage example for virtualization.
**How**:
A couple of examples in the docsite and links to codesandboxes.
**Checklist**:
> docs: add react-virtual examples

- docs/hooks/useCombobox.mdx
**What**:
Fixes the action example in the docsite for useCombobox.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1100.
**How**:
Checks if isOpen and if true then opens menu.
**Checklist**:
> docs(useCombobox): fix the action example

- typings/index.d.ts
**What**:
Accept `null` for `selectedItem` in the TS typings. Also fixed an issue by replacing `keysSoFar` which was not used anymore in `useSelect`.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1088.
**How**:
Add `| null` to `selectedItem` (state and prop), `defaultSelectedItem` and `initialSelectedItem` for `useSelect` and `useCombobox`. 
**Checklist**:
> chore(TS): accept null for selectedItem

- typings/index.d.ts
**What**:
This makes it so the argument passed to `itemToString` can be `null` for the following interfaces:
- `UseSelectProps`
- `UseComboboxProps`
- `Actions`
**Why**:
This makes them behave in line with various documentation, which states that they can receive null:
- [`useCombobox#itemToString`](https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox#itemtostring)
- [`useSelect#itemToString`](https://github.com/downshift-js/downshift/tree/master/src/hooks/useSelect#itemtostring)
- [Downshift component](https://github.com/downshift-js/downshift#itemtostring)
**How**:
I looked for all instances for `itemToString` in the typescript types and looked up their documentation to determine which ones have been specified to potentially be `null`. I then added `| null` to the …
> fix(ts): specify that itemToString can receive null

- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useSelect/__tests__/props.test.js
- src/hooks/utils.js
- typings/index.d.ts
**What**:
As discussed [here](https://github.com/downshift-js/downshift/issues/879#issuecomment-608349780) we are adding `type` to other handlers as we claim to support this already in the docs.
**Why**:
We already claim to support these. We already pass `type` in `onStateChange`.
Fixes https://github.com/downshift-js/downshift/issues/1015.
**How**:
- Add `type` in other chance handlers as well (`onIsOpenChange`, `onSelectedItemChange` etc.)
- Fix TS typings for these handlers to reflect they can have partial state + type.
- Remove `props` from the `stateReducer` call param `actionAndChanges`. Now it should be called with `{...action, changes}`, where `action` has a `type` and other data passed by the hook in dispatch.
- Also fix typings for `stateReducer` in both hooks to reflect it's …
> fix(hooks): add type to on change handler params

- typings/index.d.ts
**What**:
Make item parameter accept null for itemToString in the A11yStatusMessageOptions.
**Why**:
To finish the fixes added by https://github.com/downshift-js/downshift/pull/1075.
**How**:
Change the type for itemToString in A11yStatusMessageOptions.
**Checklist**:
> fix(TS): fix itemToString type in A11yStatusMessageOptions

- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useCombobox/reducer.js
- typings/index.d.ts
**What**:
Do not select highlighted item if the blur is performed by mouse/touch.
**Why**:
To fix https://github.com/downshift-js/downshift/issues/1010.
**How**:
Add an optional parameter to `action` in dispatch that prevents selection on mouse/touch blur. This is used in the callback passed to the hook `useMouseAndTouchTracker`.
**Checklist**:
> fix(useCombobox): prevent selection on mouse/touch blur

- src/__tests__/downshift.get-input-props.js
- src/downshift.js
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/reducer.js
**What**:
On Escape, if the menu is open, close it. If menu is closed, clear inputValue and selectedItem.
**Why**:
To close https://github.com/downshift-js/downshift/issues/719.
**How**:
In `downshift` revert to the previous behavior before the clear change was introduced.
In `useCombobox` change the reducer to clear `inputValue` and `selectedItem` if `state.isOpen` is false.
**Checklist**:
> fix: on escape, close menu and clear selection only if menu is closed

- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useCombobox/utils.js
**What**:
Make sure onSelectedItemChange triggers when selectedItem is controlled in strict mode (Fixes #1092)
**Why**:
To ensure correct functionality under react strict mode
**How**:
I found that a side-effect happens during render inside `useControlledReducer` when the `previousSelectedItemRef.current` is set.
In strict mode, because of double rendering, this executes multiple times when an item is clicked and causes a `ControlledPropUpdatedSelectedItem` action to be dispatched even though the prop wasn't updated. This action doesn't update `selectedItem` from the initial value provided through the controlled prop, so the change to it is lost (I'm not 100% sure I understood exactly now this works, but it's my best guess). 
I wrapped the side-effect in `useEffect()` as suggested in the …
> fix(useCombobox): fix onSelectedItemChange not triggering with controlled selectedItem in React.StrictMode

- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useSelect/__tests__/props.test.js
- src/hooks/utils.js
**What**:
When the dropdown is first opened with a selected item, the item should be scrolled into view and onHighlightedItemChange should be called (Fixes #1106)
**Why**:
Because the behavior is inconsistent between the first and subsequent opens.
**How**:
The useSelect `reducer` makes sure that whenever the dropdown would be closed (`isOpen: false`), the `highlightedIndex` is reset to -1 at the same time. However, if an item is selected initially, `initialState` would create a state with `isOpen: false` and `highlightedIndex` set to the item's index. This causes `onHighlightedIndexChange` not to fire on first open, as the index doesn't change from the initial state.
I've changed `initialState` to only set the `highlightedIndex` if the dropdown is already open, to keep the state …
> fix(useSelect): ensure the initial selected item is scrolled into view on first open

- README.md
- src/__tests__/downshift.get-input-props.js
- src/downshift.js
- src/hooks/useCombobox/README.md
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useCombobox/reducer.js
- src/hooks/useSelect/__tests__/props.test.js
- src/hooks/utils.js
- typings/index.d.ts
**What**:
Update downshift to v6.
**Why**:
Introduce breaking changes that fix the issues below.
Fixes https://github.com/downshift-js/downshift/issues/1088.
Fixes https://github.com/downshift-js/downshift/issues/1015.
Fixes https://github.com/downshift-js/downshift/issues/1010.
Fixes https://github.com/downshift-js/downshift/issues/719.
**How**:
**The list of breaking changes:**
BREAKING CHANGE: Update TS typings for `selectedItem` to accept `null` in both `useSelect` and `useCombobox`.
To migrate to the new change, update your types or code if necessary. `selectedItem`, `defaultSelectedItem` and `initialSelectedItem` now have `Item | null` instead of `Item` type. PR with the changes: https://github.com/downshift-js/downshift/pull/1090
BREAKING CHANGE: Update TS typings for …
> downshift v6

- docs/hooks/useCombobox.mdx
- src/hooks/useCombobox/README.md
**What**:
This adds a default type of "button" to useCombobox examples. To avoid form automatic submissions.
**Why**:
When copy pasting basic usage examples in a page that has a real form, like when using https://react-hook-form.com/ with downshift, there's a bad behavior: any button within a form has the default type of submit. Which means that every time you click on open, it submits the form.
This is hard to track/debug and could be a timesink for developers.
**How**:
**Checklist**:
Related: https://github.com/downshift-js/downshift/issues/1063
> docs(useCombobox): proposal to add button type "button"

- README.md
- package.json
- typings/index.d.ts
**What**:
Change `UseComboboxDispatchAction` `type` parameter type from `UseSelectStateChangeTypes` to `UseComboboxStateChangeTypes`.
**Why**:
To reflect the correct state change types.
Fixes https://github.com/downshift-js/downshift/issues/1122.
**How**:
Change typings
**Checklist**:
> fix(Typescript): fix UseComboboxDispatchAction type 

- typings/index.d.ts
**What**: 
Change return type of  `stateReducer()` for hooks from `State<Item>` to `Partial<State<Item>>`
**Why**:
To reflect incoming changes type.
Fixes #1122 
**How**:
Change typings
**Checklist**:
> fix(Typescript): fix stateReducer() return type for hooks

- typings/index.d.ts
**What**:
Typings were missing for `getInputProps` and `getMenuProps`  while using `useCombobox` hook with Typescript
**Why**:
To prevent compile time error from Typescript compiler
**How**:
**Checklist**:
> chore(Typescript): add type for the second argument of the appropriate getter props

- docs/hooks/useSelect.mdx
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useCombobox/reducer.js
**What**:
Call dispatch on `Enter` keydown.
Prevent event default (form submission) if menu is open.
Do not return highlightedIndex from reducer if menu is closed.
Fix the MUI example for useSelect on the docsite.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1114.
Also to fix other potential issues.
**How**:
Fix the reducer for the `useCombobox` hook.
Add itemsAsObjects to the MUI example useCombobox hook.
Check state.isOpen before returning a `highlightedIndex` in the Home/End actions.
**Checklist**:
> fix(useCombobox): dispatch on Enter keydown event

- src/hooks/useMultipleSelection/README.md
**What**:
I've fixed the syntax error in useMultipleSelection README example.
**Why**:
It's always great to have a README example which is ready to be copied/pasted.
**How**:
Just a README update.
**Checklist**:
- [ x] Documentation
Hi!
Thank you for great work on downshift.
Best regards.
> docs(useMultipleSelection): fix syntax error in README example

- .size-snapshot.json
- typings/index.d.ts
**What**:
Make `props` optional for useMultipleSelection in TS.
**Why**:
You don't need to pass `props` for this hook.
**How**:
`props?`
**Checklist**:
> fix(types): props optional for useMultipleSelect

- src/hooks/utils.js
**What**:
Replace `useEffect` with `useLayoutEffect` in `useScrollIntoView`.
**Why**:
Prevent an unnecessary double paint.
**How**:
Replace the `useEffect` with `useLayoutEffect`.
**Checklist**:
> perf(scroll): replace useEffect with useLayoutEffect

- .size-snapshot.json
- src/hooks/utils.js
**What**:
Fix https://github.com/downshift-js/downshift/issues/1211
**Why**:
To avoid warnings and make scroll work on both SSR and CSR.
**How**:
If on a browser, call `useLayoutEffect`, otherwise `useEffect` in the scroll utility.
**Checklist**:
> fix(scroll): use isomorphic effect for SSR

- .size-snapshot.json
- src/hooks/testUtils.js
- src/hooks/useCombobox/__tests__/memo.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useCombobox/testUtils.js
- src/hooks/useSelect/__tests__/memo.test.js
- src/hooks/useSelect/index.js
- src/hooks/useSelect/testUtils.js
**What**:
Based on https://github.com/downshift-js/downshift/pull/1205 and with some test changes.
Fixes https://github.com/downshift-js/downshift/issues/1178.
**Why**:
See https://github.com/downshift-js/downshift/pull/1205
**How**:
See https://github.com/downshift-js/downshift/pull/1205
**Checklist**:
> fix(hooks): prevent overwrite of itemRefs when hooks rerender

- src/hooks/useSelect/__tests__/getMenuProps.test.js
- src/hooks/useSelect/index.js
**What**:
Fixes https://github.com/downshift-js/downshift/issues/1226
Addresses dangling callback outlined in the issue above.
**Why**:
Because callbacks should be cleared on unmount.
**How**:
Cancelling the debounced function in the cleanup function of `useEffect`.
**Checklist**:
This still needs a test! Hoping for a pointer on the best approach test test this within the test suite.
> fix(useSelect): clear debounced keysSoFar callback on unmount

- src/downshift.js
- src/hooks/utils.js
- src/utils.js
**What**: This change is made to address an issue being described in [Issue-1225](https://github.com/downshift-js/downshift/issues/1255)
**Why**: otherwise `downshift` does not work properly when rendering from an iframe to the parent window using React Portal
**How**: replace `instanceof Node` with `instanceof environment.Node`
**Checklist**:
> fix(environment): use Node variable within the provided window context

- README.md
**What**: this PR adds a link to the W3.org [page](https://www.w3.org/TR/wai-aria-practices/) about ARIA.
**Why**: I was reading the README but didn't know what ARIA was, so I figured this might be useful for newcomers, specially noting that when combobox and select are mentioned in the same page, they have links to their respective sections in W3's ARIA specification.
**How**: A link was added to ARIA'S first mention in the "The Problem" README section.
**Checklist**:
> Add ARIA W3 page link to README

- src/hooks/utils.js
**What**:
Do not add a11y status on react native.
Closes https://github.com/downshift-js/downshift/issues/1257.
**Why**:
Not working and is breaking.
**How**:
Use `is.macro` as it is used in Downshift. Original PR https://github.com/downshift-js/downshift/pull/1278:
**Checklist**:
> fix(hooks): do not add a11y status on react native

- package.json
- tsconfig.json
**What**:
Remove es2020 value from tsconfig target.
Fixes https://github.com/downshift-js/downshift/issues/1303.
**Why**:
Breaking builds.
**How**:
Remove line to go back to es3 default.
**Checklist**:
> fix(tsconfig): revert target es2020

- package.json
- typings/index.d.ts
**What**:
Fixes https://github.com/downshift-js/downshift/issues/1307.
Change back to `0.0.0-semantically-released` in package json.
**Why**:
Typings are broken, we will have both the manual d.ts and generated in parallel until full migration.
**How**:
Revert the `A11yStatusMessageOptions` change.
**Checklist**:
> fix(TS): revert changes in typings index.d.ts

- README.md
Prior to this PR, the stateChangeTypes as listed in the README were not in sync with those defined in the code.
> docs: update stateChangeTypes in README

- src/hooks/useMultipleSelection/__tests__/returnProps.test.js
- src/hooks/useMultipleSelection/reducer.js
fixes #1316
**What**:
Fixing the handling of undefined/null being provided to  `useMultipleSelection`'s `removeSelectedItem` function.
**Why**:
Currently when undefined/null is provided one of the items is duplicated in `selectedItems` 
**How**:
Only modifying the `selectedItems` and `activeIndex` if `selectedItemIndex` is greater than or equal to zero
**Checklist**:
> fix(useMultipleSelect): removeSelectedItem adding duplicate items to selected items

- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/index.js
**What**:
Closes https://github.com/downshift-js/downshift/issues/1406.
**Why**:
**How**:
**Checklist**:
> fix(useCombobox): prevent default on Escape when menu is visible or input has content

- babel.config.js
- cypress.config.js
- package.json
Fixes https://github.com/downshift-js/downshift/issues/1411.
Installs and uses cypress preprocessor for cypress tests. This should allow the parsing of the code that has modules
```
[test:cypress] Error: Webpack Compilation Error
[test:cypress] ./node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js 429:27
[test:cypress] Module parse failed: Unexpected token (429:27)
```
As explained on the [cypress docsite](https://github.com/cypress-io/cypress/tree/master/npm/webpack-preprocessor). Not sure why the issue started to happen now, but this fix should probably solve it, as far as I understand from digging around.
> dev: use cypress preprocessor

- src/hooks/useCombobox/__tests__/getItemProps.test.js
- src/hooks/useCombobox/index.js
**What**:
Closes https://github.com/downshift-js/downshift/issues/1409.
**Why**:
Before these changes, when an item was selected, the input was blurred, and the input received focus after the dispatch event in the item click handler.
It worked fine apart from the corner case in https://github.com/downshift-js/downshift/issues/1409 and https://github.com/downshift-js/downshift/issues/1405. There, when input received focus from the handler, it called OpenMenu, which was called with the previous `selectedItem`, since it was controlled, and the prop did not get updated yet. OpenMenu was called before this controlled prop update.
**How**:
To fix it, instead of adding focus manually after triggering item click state update, we are preventing the blur altogether via event.preventDefault() in the …
> fix(useCombobox): do not blur on item click

- src/hooks/MIGRATION_V7.md
- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/index.js
- src/hooks/useSelect/testUtils.js
**What**:
Fixes https://github.com/downshift-js/downshift/issues/1428.
**Why**:
As we don't use `<button>` anymore in building `useSelect` we have to trigger the click manually on Enter/SpaceBar.
**How**:
Trigger the click state change on Enter/SpaceBar if menu is closed.
**Checklist**:
> fix(useSelect): trigger click manually on Enter / Space

- other/manual-releases.md
There was an issue with a patch release, so this manual-releases.md
change is to release a new patch version.
Reference: [#<the number of a relevant pull request, issue, or commit>](https://github.com/downshift-js/downshift/commit/061b5b190c7d3803aa6d0c751e7599e01bd1f45d)
> fix: manually release patch version

- typings/index.d.ts
**What**:
Make `refKey` optional in `GetRootPropsOptions`.
**Why**:
Closes https://github.com/downshift-js/downshift/issues/1354.
The `refKey` prop is treated as optional in downshift.
**How**:
Make it optional in the typings.
**Checklist**:
> fix(TS): make refKey optional in GetRootPropsOptions

- src/hooks/useCombobox/README.md
- src/hooks/useSelect/README.md
**What**: Remove reference to usage of shift modifier with arrow keys from useSelect and useCombobox docs
**Why**: Since v7, using shift modifier key + arrow key is not supported.
> docs: align docs with v7

- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/index.js
- src/hooks/useSelect/utils.ts
**What**:
Improve the highlight by character keys algorithm of useSelect.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1163.
Fixes https://github.com/downshift-js/downshift/issues/1339.
**How**:
1. If we hit Space when select is closed, it will trigger ToggleButtonClick, and will open the menu. If it's open, it will close it, with the same state change type, and select the highlighted item, if any.
2. If we hit Space after we typed at least one character key in the last 500ms, it will count as the next character key of the search query, and will trigger the ToggleButtonKeyDownCharacter state change type.
3. If we hit character key for the first time with the select open, it will search to highlight the first item starting with that character, and it will begin the …
> feat(useSelect): improve highlight by character keys algorithm

- src/hooks/useMultipleSelection/__tests__/getSelectedItemProps.test.js
- src/hooks/useMultipleSelection/__tests__/props.test.js
- src/hooks/useMultipleSelection/reducer.js
**What**:
If activeIndex is -1, do not react on Backspace/Delete keydown from selected item element.
Even when a selected item is no properly focused (not active), it can still receive keydowns, and the previous implementation did not account for it, resulting in adding duplicated selected items.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1138.
**How**:
Exit fast from reducer's SelectedItemKeyDownBackspace and SelectedItemKeyDownDelete handler if activeIndex is -1.
**Checklist**:
> fix(useMultipleSelection): prevent adding items on Backspace/Delete without activeIndex

- cypress.config.js
- docusaurus.config.js
- package.json
**What**:
This PR changes the JS to be transpiled.
**Why**:
Unfortunately at the moment we cannot use downshift because it is tripping up our storybook and webpack builds due to some syntax that is too new, such as `??`.
**How**:
Configure the `browserlist` in package.json.
**Checklist**:
> fix: set `browserlist` so that js files are transpiled

- src/hooks/utils.js
**What**:
Do not add mouse and touch events from useMouseAndTouchTracker in the case of React native.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1315.
**How**:
Check in useMouseAndTouchTracker if isReactNative, and return directly from the useEffect. The return values will always be false on react Native, but this is also done in Downshift, so it's consistent.
**Checklist**:
> fix(hooks): do not add mouse and touch events in React native

- src/hooks/__tests__/utils.test.js
- src/hooks/useCombobox/index.js
- src/hooks/utils.js
**What**:
Use `environment` instead of `document` in a `useCombobox` line.
**Why**:
In case there is no `document` available, like in React Native, and in other situations when `document` needs to be replaced by the `environment` prop.
**How**:
Replace `document` with `environment.document`.
**Checklist**:
> fix(useCombobox): use environment instead of document

- src/hooks/useMultipleSelection/index.js
**What**:
Do not set removal status message in useMultipleSelection when on React Native.
**Why**:
It was crashing in React Native when an element was removed.
**How**:
`isReactNative` boolean check inside the effect for setting the a11y status message.
**Checklist**:
> fix(useMultipleSelection): do not crash in react native

- src/hooks/useCombobox/utils.js
I noticed we are getting some flickering when updating the value of a combobox built using downshift. After much debugging the culprit seems to be the logic in `useControlledReducer`. 
We store the ID of the selected item as a query parameter and when updating the value through Next.js's router we get the flickering behavior. If I store the id in local state, the flickering doesn't happen.
As far as I can tell, the reason we see the flickering is because there is an extra render and this effect gets called again before the prop updated.
This PR changes to only run the effect when `props.selectedItem` or `state.selectedItem` change. This fixes the issue in our case. Making an effect run on every render seems not ideal anyway.
**Checklist**:
> fix(useCombobox): controlled selectedItem extra renders

- src/hooks/__tests__/utils.test.js
- src/hooks/useCombobox/__tests__/getItemProps.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useMultipleSelection/__tests__/getSelectedItemProps.test.js
- src/hooks/useMultipleSelection/index.js
- src/hooks/useSelect/__tests__/getItemProps.test.js
- src/hooks/useSelect/index.js
- src/hooks/utils.js
**What**:
Fix the `index` and `item` function called in the `getItemProps` and `getSelectedItemProps`.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1469.
Should handle all cases now.
**How**:
If both are passed, return both.
If only one in passed, return the other based on the items and the passed prop.
If none is passed, throw error.
**Checklist**:
> fix(hooks): correctly compute item and index in getter function

- src/hooks/useCombobox/README.md
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/reducer.js
- src/hooks/useCombobox/utils.js
- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/reducer.js
- src/hooks/utils.js
**What**:
Fix the behaviour of default props in hooks to only be called on selection, and only be applied if `items` is not empty and and the `defaultHighlightedIndex` is valid.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1223.
**How**:
Check if a selection should be performed by the rule `props.items?.length && highlightedIndex >= 0`
If a selection should be performed, the resulting state should be:
```js
selectedItem: props.items[highlightedIndex],
isOpen: getDefaultValue(props, 'isOpen'),
highlightedIndex: getDefaultValue(props, 'highlightedIndex'),
...(inputValue && {
inputValue: props.itemToString(props.items[highlightedIndex]),
}),
```
**Checklist**:
> fix(defaultProps): only select if there are items and one is highlighted

- src/hooks/useCombobox/README.md
- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useCombobox/utils.js
- typings/index.d.ts
**What**:
Support `selectedItemChanged` in `useCombobox`
**Why**:
To override default value of referential comparison when `ControlledPropUpdatedSelectedItem` should be triggered or not.
**How**:
Replace the referential comparison with calling the prop `selectedItemChanged`.
Add default value for `selectedItemChanged` to compare reference, in order to keep the default implementation.
**Checklist**:
> feat(useCombobox): selectedItemChanged support

- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/index.js
**What**:
InputBlur action should return `selectedItem` only from Tab/Shift+Tab and not from clicking outside. However, before this change, if your click outside is to change browser tab, the current `highlightedIndex` is selected when returning to the page. This PR is to prevent that behaviour.
Fixes #1471.
**How**:
This PR updates the `InputBlur` handler on `useCombobox` to rely on the `event.relatedTarget`. In a blur event, this is set to the element receiving focus which is simply `null` when switching tabs because focus is no longer in that window.
**Checklist**:
> fix(useCombobox): ensure highlighted item is not selected on browser tab change

- package.json
- src/downshift.js
- src/hooks/useCombobox/index.js
- src/hooks/useSelect/index.js
- src/is.macro.js
**What**:
Support React Native Web in the hooks and in Downshift.
**Why**:
React Native is supported fully, we also should support React Native Web.
**How**:
As recommended in https://github.com/downshift-js/downshift/issues/1315#issuecomment-1474289581, we will create a react native web build and use the isReactNativeWeb variable to return the correct code in React native web (`onPress`, `event.nativeEvent.text` etc).
**Checklist**:
> feat(reactNativeWeb): support in Downshift and hooks

- README.md
- src/__tests__/downshift.aria.js
- src/downshift.js
- src/hooks/useCombobox/README.md
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/__tests__/getMenuProps.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useSelect/README.md
- src/hooks/useSelect/__tests__/getMenuProps.test.js
- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/index.js
**What**:
If `aria-label` is passed to `getInputProps`, `getMenuProps` or `getToggleButtonProps` (from `useSelect`), the getter function will not return `aria-labelledby`.
**Why**:
Consistency between Downshift and hooks, between getter props that return `aria-labelledby` attributes.
**How**:
Check if `aria-label` is provided and if not, then return `aria-labelldby`. This applies to:
- Downshift getMenuProps and getInputProps.
- useSelect getToggleButtonProps and getMenuProps.
- useCombobox getInputProps and getMenuProps.
The return value type will be provided in https://github.com/downshift-js/downshift/pull/1482.
**Checklist**:
> feat: getter prop with aria-label will not add aria-labelledby

- package.json
- src/downshift.js
- src/hooks/MIGRATION_V8.md
- src/hooks/useCombobox/index.js
- test/basic.test.tsx
- test/downshift.test.tsx
- test/useCombobox.test.tsx
- test/useMultipleSelect.test.tsx
- test/useSelect.test.tsx
- typings/index.d.ts
**What**:
Replace `any` with proper return values in getter props Typescript types.
Return value should be Downshift returns + Props passed as Options, which, in turn, should be HTML props for those elements + any optional props passed by the user.
**Why**:
To better reflect the return value of the getter props.
Use cases:
- props accepted by getter function should stay the same.
- props returned by getter function should be the ones returned by Downshift / hooks.
- ~~if prop types are passed to getter that have a different type from the one returned by Downshift / hooks, the type of the returned prop should be changed. For example, `getLabelProps({htmlFor: true})` will have the return type `{id: string, htmlFor: true}`.~~
- returned props should contain the custom props passed to the …
> types: return values for getter props

- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/index.js
**What**:
Tabbing with an element highlighted should select that element, even if the combobox is the last element in the tab order and the focus ends up on `body`.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1515
**How**:
The bug is a regression from https://github.com/downshift-js/downshift/pull/1484.
The fix in the PR above handles correctly the case when blur is performed by tab change, and in this case the element should not be selected. Blur by tab change is detected via `event.relatedTarget === null`. However, tabbing from the last element in the tab order also has `event.relatedTarget === null` so we need to distinguish between these two cases. The fix is to also check the `environment.document.activeElement === environment.document.body`.
**Checklist**:
> fix(useCombobox): tab to body should select element

- src/hooks/useCombobox/index.js
Leftover from https://github.com/downshift-js/downshift/pull/1517, the useCallback deps array also needs to be updated.
> fix(useCombobox): exhaustive deps for getInputProps

- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/index.js
**What**:
Focus the toggle element if the menu is opened initially.
**Why**:
Similar behaviour to useCombobox and the input focus.
**How**:
Same implementation as for useCombobox.
**Checklist**:
> feat(useSelect): focus toggle when opened initially

- typings/index.d.ts
**What**:
Adds the generic type parameter for React.RefObject.
**Why**:
In `@types/react`, the type definition looks like this:
```
interface RefObject<T> {
readonly current: T | null;
}
```
This means the `T` generic parameter needs to be set mandatorily. 
In case `skipLibCheck` is **not** set to `true`, this causes a typescript type error:
```
../../node_modules/downshift/typings/index.d.ts:112:9 - error TS2314: Generic type 'RefObject<T>' requires 1 type argument(s).
112   ref?: React.RefObject
~~~~~~~~~~~~~~~
```
**How**:
I've added `any` as type parameter, which is not ideal but avoids adding a generic type parameter to the parent types (e.g. `GetRootPropsOptions`).
Open for better suggestions.
**Checklist**:
> fix(typescript): missing generic parameter of React.RefObject

- src/downshift.js
- src/hooks/utils.js
**What**:
Keep default prop `environment` as `undefined` in React Native.
Closes https://github.com/downshift-js/downshift/issues/1525.
**Why**:
In React Native, we do have a defined `window` object, but does not have the properties we need.
**How**:
Check `isReactNative` in both Downshift and the hooks.
**Checklist**:
> fix(defaultProps): use undefined environment on React Native

- src/hooks/useCombobox/index.js
- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/index.js
**What**:
Prevent default on getItemProps onMouseDown for useSelect.
https://github.com/downshift-js/downshift/issues/1537
**Why**:
Keep the focus on the toggle button when item is selected by mouse click.
**How**:
This was overlooked since for very long the focus strategy with useSelect was different (switch between toggle and menu).
**Checklist**:
> fix(useSelect): preventDefault on item props onMouseDown

- typings/index.d.ts
**What**:
Add `onPress` optional type to the toggle button functions parameter.
**Why**:
The getToggleButtonProps can also take  onPress in RN which does not exist in the current types. 
**How**:
Add the type to both the downshift/useCombobox and useSelect typ.es
**Checklist**:
> fix(typescript): add onPress to toggle button props parameter

- src/hooks/useCombobox/index.js
- src/hooks/useCombobox/utils.js
- src/hooks/useMultipleSelection/index.js
- src/hooks/useSelect/index.js
- src/hooks/utils.js
**What**:
Use function to create initial state in reducer.
**Why**:
Avoid recreating the initial state on every render. https://react.dev/reference/react/useReducer#avoiding-recreating-the-initial-state
**How**:
Refactor the usage according to the React API
**Checklist**:
> fix(hooks): use createInitialState in reducer

- README.md
**What**:
fix GitHub workflow badge URL
**Why**:
GitHub workflow status badge was broken.
**How**:
See https://github.com/badges/shields/issues/8671
**Checklist**:
> dev(readme): fix GitHub workflow badge URL

- src/hooks/useSelect/README.md
- src/hooks/useSelect/__tests__/getLabelProps.test.js
- src/hooks/useSelect/index.js
- typings/index.d.ts
**What**:
Focus the toggle element when the `<label>` is clicked, for useSelect.
**Why**:
Closes https://github.com/downshift-js/downshift/issues/1557.
Native `<select>` works the same way with a `<label>`
ARIA also is on board: https://github.com/w3c/aria-practices/issues/2859
**How**:
Add a custom `onClick` handler to useSelect `getLabelProps` that focuses the toggle element.
**Checklist**:
> feat(useSelect): focus toggle on label click

- src/hooks/useSelect/__tests__/getLabelProps.test.js
- typings/index.d.ts
**What**:
FIx a type change from https://github.com/downshift-js/downshift/pull/1561.
**Why**:
The type change was meant to be on the returned value, not the props
**How**:
**Checklist**:
> fix(useSelect): correct getLabelProps return type

- src/hooks/__tests__/utils.test.js
- src/hooks/useCombobox/__tests__/getItemProps.test.js
- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useCombobox/utils.js
- src/hooks/useMultipleSelection/index.js
- src/hooks/useSelect/__tests__/getItemProps.test.js
- src/hooks/useSelect/index.js
- src/hooks/utils.js
- src/utils.js
**What**:
Don't call the onMouseMove handler when a touch event is detected.
**Why**:
Not really needed, since on mobile we don't highlight items with touch.
It also causes a sequence of batched dispatch calls that are difficult to understand and, most probably, wrong.
On mobile, when touching to select an item, we had a couple of batched dispatch calls:
1. item click
2. item mouse move + item click.
To me, it did not make sense. On non-mobile, it was fine, mouse move when mouse actually moved, and click after click. Nothing else.
Now we should only get itemClick on mobile when we touch to select an item.
Closes https://github.com/downshift-js/downshift/issues/1540.
Closes https://github.com/downshift-js/downshift/issues/1566.
Closes https://github.com/downshift-js/downshift/issues/1447. …
> fix(onMouseMove): only call handler on non-touch devices

- src/hooks/useMultipleSelection/index.js
**What**: fixes issue causing combobox to grab focus on render
**Why**: Closes: #1574
**How**: The latest release adds `isInitalMount` to the dependency array. Whichs causes it to rerender when `isInitialMount`  is set to false and triggering `.focus.`
**Checklist**:
> fix: fixes issue causing combobox to grab focus on render

- src/hooks/useCombobox/README.md
- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useCombobox/utils.js
- src/hooks/useMultipleSelection/README.md
- src/hooks/useMultipleSelection/index.js
- src/hooks/useMultipleSelection/reducer.js
- src/hooks/useMultipleSelection/utils.js
- src/hooks/useSelect/README.md
- src/hooks/useSelect/reducer.js
- src/hooks/utils.js
- typings/index.d.ts
**What**:
Reboot https://github.com/downshift-js/downshift/pull/1529 without the breaking change part.
**Why**:
Closes https://github.com/downshift-js/downshift/issues/1495.
**How**:
Initially have both itemToKey and selectedItemChanged props but warn that the latter is going to be deprecated.
**Checklist**:
> feat(hooks): itemToKey prop

- src/hooks/useCombobox/README.md
**What**:
Document the workaround for https://github.com/downshift-js/downshift/issues/1108.
**Why**:
No current way to properly fix this in the hooks.
**How**:
**Checklist**:
> docs(useCombobox): cursor jump workaround

- src/hooks/MIGRATION_V9.md
- test/useCombobox.test.tsx
- typings/index.d.ts
**What**:
Improve the type of the onChange options parameter to reflect that individual onChange functions are called with non-optional state values.
**Why**:
For example, onIsOpenChange will always be called with `isOpen`, so the type will be {type, isOpen, highlightedIndex?, inputValue?, ...}
**How**:
Change the typings.ts
**Checklist**:
> types(hooks): improve Typescript for onChange funtions

- src/hooks/__tests__/utils.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useSelect/index.js
- src/hooks/utils.js
- src/utils.js
**What**:
Remove the mouse and touch event handlers on unmount.
**Why**:
The previous implementation was removing the handlers and adding new ones on each isOpen change.
**How**:
Removed the isOpen dependency from the hook and moved the logic to the callback passed by useCombobox and useSelect.
**Checklist**:
> feat(hooks): remove mouse and touch events on unmount

- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useMultipleSelection/README.md
- src/hooks/useMultipleSelection/__tests__/props.test.js
- src/hooks/useSelect/__tests__/props.test.js
- src/hooks/utils.js
**What**:
Fix the dependency array in the useEffect that triggers the a11y status change.
**Why**:
The parameter we passed to updateA11yStatus was an array, and we wrapped that array into another array which we passed to useEffect. Resulted in a broken behaviour.
**How**:
Pass the dependency array directly to the useEffect hook.
**Checklist**:
> fix(a11yStatus): pass correct dependency array

- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useSelect/__tests__/props.test.js
- src/hooks/utils.js
**What**:
Check if items are disabled before highlighting them, when opening the menu with initialHighlightedIndex or defaultHighlightedIndex.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1584.
**How**:
Check if the items are disabled before returning defaultHighlightedIndex / initialHighlightedIndex as the highlightedIndex on menu open.
**Checklist**:
> fix(hooks): do not highlight disabled items on menu open

- typings/index.d.ts
**What**:
Change `index` with `number` as `highlightedIndex` type.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1590.
**How**:
Change the type.
**Checklist**:
> fix(types): replace index with number

- src/hooks/reducer.js
- src/hooks/useCombobox/__tests__/__snapshots__/getInputProps.test.js.snap
- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/__tests__/getItemProps.test.js
- src/hooks/useCombobox/__tests__/props.test.js
- src/hooks/useCombobox/__tests__/returnProps.test.js
- src/hooks/useCombobox/reducer.js
- src/hooks/useSelect/__tests__/__snapshots__/getToggleButtonProps.test.js.snap
- src/hooks/useSelect/__tests__/getItemProps.test.js
- src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
- src/hooks/useSelect/__tests__/props.test.js
- src/hooks/useSelect/__tests__/returnProps.test.js
- src/hooks/useSelect/reducer.js
- src/hooks/utils.js
**What**:
Fix all the scenarios when an item can be highlighted even if it's disabled.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1599.
**How**:
Check if item is disabled when setting the highlightedIndex via reset, imperative set, as well as user actions such as open on click / arrow down and up.
**Checklist**:
> fix(highlightedIndex): do not highlight disabled items

- src/hooks/useCombobox/__tests__/getItemProps.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useSelect/__tests__/getItemProps.test.js
- src/hooks/useSelect/index.js
- src/hooks/useSelect/testUtils.js
**What**:
Return a `boolean` for `aria-selected` as the documentation / types suggest. Affects for the hooks `useSelect` and `useCombobox`.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1596.
**How**:
Update the return value and the unit tests.
**Checklist**:
> fix(hooks): return boolean for aria-selected

- src/hooks/__tests__/__snapshots__/utils.test.js.snap
- src/hooks/__tests__/utils.test.js
- src/hooks/useCombobox/index.js
- src/hooks/useSelect/index.js
- src/hooks/utils.js
Alternative for https://github.com/downshift-js/downshift/pull/1609. It should avoid adding and removing event listeners on each render, while fixing the initial issue.
Closes https://github.com/downshift-js/downshift/issues/1600.
> fix(useMouseAndTouchTrackers): dependency array

- src/hooks/useCombobox/__tests__/getInputProps.test.js
- src/hooks/useCombobox/__tests__/getMenuProps.test.js
- src/hooks/useMultipleSelection/__tests__/getDropdownProps.test.js
- src/hooks/utils.js
**What**:
The suppressRefError from hooks works, this PR just improves the code and adds a few more tests.
**Why**:
**How**:
**Checklist**:
> fix(hooks): suppressRefError improvement

- typings/index.d.ts
**What**:
Add `null` to the `selectedItem` type in `onSelectedItemChange` for both combobox and select.
**Why**:
Closes https://github.com/downshift-js/downshift/issues/1639.
**How**:
Add type.
**Checklist**:
> fix(types): add null to selectedItem type

- README.md
- src/hooks/useCombobox/README.md
- src/hooks/useMultipleSelection/README.md
- src/hooks/useSelect/README.md
**What**:
Change the codesandobx links to keep the module view.
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1598
**How**:
Check issue for details.
**Checklist**:
> docs(codesandbox): fix links to keep module view
