downshift-js/downshift

src/utils.js

**What**:
Fixes https://github.com/paypal/react-autocompletely/issues/35
**Why**:
It broke when no scrollParent was found.
**How**:
Checks for the existence of scrollParent now.
**Checklist**:

fix(scrollIntoView): make sure scrollParent exists

---

src/autocomplete.js
src/input.js
src/utils.js

Closes https://github.com/paypal/react-autocompletely/issues/32
Missing fixes in https://github.com/paypal/react-autocompletely/pull/46
Reference: https://github.com/paypal/react-autocompletely/pull/46#discussion_r130191005

Missing fixes in #46

---

README.md
src/autocomplete.js
src/utils.js

**What**:
`scrollIntoView` was being all wonky and I forgot to push a README change.
**Why**:
`scrollIntoView` is now more robust, and will also highlight and scroll to the `activeElement` if available.
**How**:
Updated the utils to handle `scrollIntoView` better as well as added a method to highlight the current selected item. Pulled some inspiration from [this gist](https://gist.github.com/hsablonniere/2581101) for the `scrollIntoView` stuff.
**Checklist**:

Post major cleanup fixes

---

.all-contributorsrc
README.md

**What**: Add Spectre.css example link
**Why**: Provides another example for users to reference, in the style of a Spectre.css `Autocomplete` component.
**How**: Update `Examples` section in `README.md`
**Checklist**:

add Spectre.css example, update contributors

---

README.md

autocomplete doesn't render a div anymore

---

README.md
src/autocomplete.js
stories/examples/apollo.js
stories/examples/axios.js
stories/examples/basic.js
stories/examples/react-instantsearch.js
stories/examples/react-popper.js
stories/examples/semantic-ui.js

**What**:
Related to https://github.com/paypal/react-kadabra/issues/61
**Why**:
So we can build more complex menus that allow selecting multiple values.
**How**:
I followed how the browser handles `multiple` and `value`. When `multiple` is `true`, we handle value as an array. I switched the API from `selectedItem` -> `value` because I think this is a little more clear since you are technically selecting the value of your item[s]. This is also how other select menus like react-select handle this so it seemed like a safe change. I changed `value` -> `inputValue` which I think is more clear as well.
**Checklist**:
I was able to build a select menu, a multi-select, an autocomplete, and a simple dropdown menu with these changes. It's pretty cool how powerful, but simple it is! I _think_ this …

feat(multiple-prop): added the ability to select multiple values

---

README.md
src/autocomplete.js
src/utils.js
stories/examples/basic.js

**What**: add `getLabelProps` function
**Why**: This is useful for encouraging accessibility
Closes #38
**How**: Add the method. Had to do some validation to avoid footguns. Added docs
**Checklist**:

feat(label): add getLabelProps

---

.babelrc

Closes #49
**What**: Change the babel config
**Why**:  I realized that this was still set up to compile down to node v4 (like most of my projects) but most of my projects are not meant for the browser... So this fixes that :smile: This will now compile down to es5.
**How**: Remove the options to make it compile down to es5 (which is the default)
**Checklist**:

fix: compile to es5

---

README.md
src/autocomplete.js
src/set-a11y-status.js
stories/examples/controlled.js

Ref: #79
**What**: Fixes some things in the default implementation of `getA11yStatusMessage`
**Why**: So the default is more accessible
**How**: Magic ✨
**Checklist**:

fix(a11y): improve `getA11yStatusMessage`

---

src/autocomplete.js
src/utils.js

**What**:
Pertaining to https://github.com/paypal/downshift/issues/79.
**Why**:
This adds ARIA support for activedescendant.
**How**:
I used this [article from w3](https://www.w3.org/WAI/GL/wiki/Using_aria-activedescendant_to_allow_changes_in_focus_within_widgets_to_be_communicated_to_Assistive_Technology) as a guide. I ended up creating a unique `id` that could be used throughout the component, which ended up simplifying some things, so I was able to remove some code 🎉 let me know if I wasn't supposed to remove something, everything looked ok to remove. I went with a smaller id name as well, `downshift` abbreviated to `ds`. I personally like smaller id's so it keeps devtools cleaner and easier to digest, but I can change this to whatever, just let me know.
**Checklist**:

feat(activedescendant): add aria-activedescendant support

---

src/autocomplete.js
src/utils.js

I just wanted to change a few things 🤷‍♂️

chore: refactor things to be more better? 🙃

---

README.md
src/downshift.js

**What**: This removes the multiple props. 
**Why**: Ref #93
**How**: Search for `multiple` in the project and remove it!
**Checklist**:

fix(multiple): remove it

---

README.md
src/__tests__/basic.js
src/__tests__/input-keyboard-handlers.js
src/downshift.js

test: add some tests!

---

src/__tests__/.eslintrc
src/__tests__/__snapshots__/get-root-props.js.snap
src/__tests__/get-root-props.js
src/__tests__/input-keyboard-handlers.js
src/downshift.js

**What**: Adds tests for the render method
**Why**: To make us more confident
**How**: Jest!
**Checklist**:

test: add tests for the render method

---

src/__mocks__/set-a11y-status.js
src/__tests__/lifecycle.js
src/downshift.js
src/utils.js

test(lifcycle): add tests for the lifecycle methods we use

---

src/__tests__/__snapshots__/set-a11y-status.js.snap
src/__tests__/set-a11y-status.js
src/__tests__/utils.get-a11y-status-message.js
src/__tests__/utils.scroll-into-view.js
src/downshift.js
src/set-a11y-status.js
src/utils.js

test(utils): add tests to the utils

---

jest.config.js
src/__tests__/__snapshots__/downshift.get-label-props.js.snap
src/__tests__/downshift.get-input-props.js
src/__tests__/downshift.get-item-props.js
src/__tests__/downshift.get-label-props.js
src/__tests__/downshift.misc.js
src/downshift.js

Closes #41!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

test: 100% code coverage!!!

---

package-scripts.js
package.json
src/__tests__/downshift.get-input-props.js
src/downshift.js

This brings paste/cut support out of the box :+1:
Also, improve the storybook build.
**What**:
**Why**:
**How**:
**Checklist**:

feat(input): open whenever the value in the input changes.

---

src/__tests__/downshift.lifecycle.js
src/downshift.js
stories/examples/apollo.js
stories/examples/axios.js
stories/examples/semantic-ui.js

fix(render): should only render when state/props actually change

---

src/__tests__/downshift.lifecycle.js
src/downshift.js

fix: update `inputValue` when `selectedItem` is controlled

---

CONTRIBUTING.md

**What**:
Adds documentation to get Storybook dependencies installed, as discussed in #125.
I added as a sub-section to "Project setup" as this would be a natural next-step after forking/cloning the project.
Let me know if the copy is ok or feel free to change as needed. 🙂
**Why**:
Ran into errors when first trying to load up Storybook.
**How**:
**Checklist**:

Added documentation for Storybook

---

src/__tests__/downshift.get-input-props.js
src/downshift.js

Ref #119 cc @jgoux
**What**: This removes checking whether there's an item at index `0`.
**Why**: In virtualized lists there is often not an item at index `0`.
**How**: Also, we can ensure that there will always be an `items` array so we can just remove that function altogether and get items by their index from `this.items`. Turns out this is much simpler :smile:
**Checklist**:

fix: improve integration with virtualized lists

---

src/__tests__/downshift.misc.js
src/downshift.js

**What**: Fix #133
**Why**: So the onChange function will be called when passing a null selectedItem
**How**: By making a check for onChange's argument more strict (null being falsy in JS)
**Checklist**:

Make onChangeArg more strict

---

src/__tests__/__snapshots__/downshift.get-item-props.js.snap
src/__tests__/downshift.get-item-props.js
src/downshift.js
src/utils.js

**What**: Add validation for `getItemProps`
**Why**: Because forgetting the `item` and `index` is easy to do.
**How**: Awesome default params trick :wink:
**Checklist**:

feat: add item props validation

---

src/index.js

Address a potential issue from TS imports referenced from #56

update entry file for ts consumption

---

README.md
src/__tests__/downshift.misc.js
src/downshift.js
stories/config.js
stories/examples/react-autosuggest.js

This is an undocumented API, but I think it'll be really useful for some
use cases so we'll try to support it.
I also kinda broke a few APIs in the process. Shouldn't impact anyone,
but it is technically different. Please see the changes in the README.
**What**: add a state change type to everything
**Why**: To support a few edge cases #53 
**How**: Changing the APIs of several actions to accept `otherStateToSet` which can have a `type` property.
**Checklist**:

feat(stateChangeTypes): add a state change type to everything

---

typings/index.d.ts

This updates the TS typings for `onChange`, `onStateChange` (f3e82ad2fe17561660a22cd79ff25c34318f038f), and adds typings for `onUserAction` (063347e32256a8084748d35d476a3ad865266cdd)

update args for onChange, onStateChange, and onUserAction

---

README.md
src/__tests__/__snapshots__/downshift.get-item-props.js.snap
src/__tests__/downshift.get-item-props.js
src/downshift.js
src/utils.js
stories/examples/apollo.js
stories/examples/axios.js
stories/examples/basic.js
stories/examples/controlled.js
stories/examples/react-autosuggest.js
stories/examples/react-instantsearch.js
stories/examples/react-popper.js
stories/examples/semantic-ui.js

**What**: This makes indexes optional
**Why**: So @souporserious doesn't feel like he needs to make another dropdown implementation because [grouping is hardish with downshift](https://twitter.com/souporserious/status/902243143843700736) :wink:
**How**: default `index` to the `indexOf` after pushing an item onto the `items`. Going with `indexOf` rather than `this.items.length - 1` because who knows 🤷‍♂️
**Checklist**:

feat(index): make index optional

---

README.md

Probably want to squash the commits in my PR.  As always when you try to rush something you make mistakes :)

Add section/option group example to README

---

stories/examples/multiple.js
test/basic.test.tsx
test/custom.test.tsx
tsconfig.json

**What**:
* Fix TypeScript compilation error
* Fix eslint error with JSDocs
**Why**:
The Travis CI build is currently broken on these 2 issues.
**How**:
* Add tsconfig to error on unused imports to help identify invalid usages and then removed them
* Added JSDoc `@param` and `@return` declarations
**Checklist**:

Typescript unused imports

---

README.md

I think this may be beneficial to others. I needed a way to search like in text editors, wanted to give back!
**What**: Fuzzy matching like SublimeText, VSCode, and Atom
**Why**: To add example to README
**How**: Added to README and verified the example works in CodeSandbox as intended.
**Checklist**:

Add example for fuzzy matching

---

README.md
src/__tests__/downshift.misc.js
src/downshift.js

Ref https://github.com/paypal/downshift/issues/38#issuecomment-331519762 cc @CMTegner
**What**: This adds an `id` prop and docs for how to deal with server side rendering and avoiding the checksum error with downshift.
**Why**: So folks aren't confused.
**How**: switch from a member property to a prop.
**Checklist**:

feat(id): add id prop for improved SSR

---

typings/index.d.ts

**What**: Add typing for `id` prop
**Why**: To keep TypeScript types in sync with the API
**How**: By adding the prop to the `DownshiftProps` interface
**Checklist**:
Minor thing: I wasn't sure if this should be classified as **feat** or as something else. I just went with **feat**, but let's change it if we need to.

feat(id): Add typing for id prop

---

README.md

**What**: Fixing typo.
**Why**: I am pretty sure it's a typo.
**Checklist**:

typo in readme: things => thinks

---

README.md

**What**:
Update link to codesandbox example for windowing
**Why**:
Because it was linking to an incorrect url
**How**:
Using the online readme editor 🙈
**Checklist**:
I didn't add myself to the contributors table because I'm a little bit lazy. Also edited via GitHub editor
so not in my dev environment to run all the cool commands and stuff.

Fix codesandbox example for windowing

---

README.md

**What**: add a select example with bootstrap
**Why**: Examples are helpful
**How**: Add an item to the examples list
**Checklist**:

docs(examples): add select example with bootstrap

---

stories/config.js
stories/examples/dropdown.js

**What**: Added a simple dropdown example
**Why**: Couldn't find one
**How**: Added a story to storybook
**Checklist**:

Add simple dropdown example.

---

README.md

**What**: Adds an example of a higher order component
**Why**: for fun
**How**: add a link to a codesandbox
**Checklist**:

docs(examples): add higher order component for fun

---

README.md

**What**: Update Examples list in `README.md`
**Why**: I fixed an error in my Codesandbox example, so I am adding the sandbox URL back.
**How**: Uncomment URL, move back into list
**Checklist**:
I (finally) fixed up my [Downshift/Spectre.css example](https://codesandbox.io/embed/M89KQOBRB), so I'm adding it back to the README.

Uncomment URL of downshift x spectre.css demo after fix

---

README.md
src/__tests__/downshift.props.js
src/downshift.js

**What**:
callback is called whenever an item is selected, regardless of prior selected item.
https://github.com/paypal/downshift/issues/232
**Why**:
Allows to react to every selection, even when the value does not change: https://github.com/paypal/downshift/issues/232
**Checklist**:

feat: add onSelect callback

---

typings/index.d.ts

Add render prop to typings

---

README.md

**What**: Removed backticks around `selectedItem`.
**Why**: No other props are written with backticks.
**How**: I removed the backticks.
**Checklist**:

Make README props formatting consistent

---

.all-contributorsrc
README.md
src/__tests__/utils.scroll-into-view.js
src/utils.js

**What**: Fixes #274
**Why**: See #274. Scrolling was weird when going from last to first item with arrow keys.
**How**: I added a change I used in my project, and then worked on figuring out the unit tests. On reviewing the unit tests I realized the intent of the previous code was meant for multiple cases when the item is above the current viewport. I worked out that there are three cases. They are hard to explain, so I made an image to better explain.
* The scrollable parent is above the viewport, and the item is above that parent
* The scrollable parent is above the viewport, and the item is above the viewport, but below the parent
* The scrollable parent is within the viewport, but the item is above the viewport
The first two simplified into the same equation after working them out, …

fixes scroll into view cases above viewport

---

README.md

Update readme with link to Episode 79: Kent C. Dodds - Building Reusable React Components with Render Props.
**What**:
Add link to podcast episode 79 to readme.
**Why**:
To help newcomers easily learn about downshift and how it came to be.
**How**:
Basic text editing in github.
**Checklist**:

Add link to podcast resource.

---

test/basic.test.tsx
typings/index.d.ts

**What**: Added a property
**Why**: To address #275
**How**: Modified `index.d.ts`
**Checklist**:

feat(TypeScript): add `StateChangeOptions.type` (#275)

---

README.md

As suggested here: https://twitter.com/kentcdodds/status/948558412001902592

[Docs] Link bindings library for ReasonML

---

src/__tests__/downshift.get-button-props.js
src/downshift.js

**What**:
This fixes issue [#277](https://github.com/paypal/downshift/issues/277).
**Why**:
For case with Button: Menu is not closed when TAB is pressed.
**How**:
Add onBlur event handler to ButtonProps(implemented exactly as onBlur handler for InputProps).
**Checklist**:

Add onBlur event handler to ButtonProps

---

src/downshift.js

Followup to https://github.com/paypal/downshift/pull/265#issuecomment-363553862
**Checklist**:

fix(cleanup): removed some leftover unused internal method

---

stories/examples/react-instantsearch.js
stories/package.json

**What**: update the major version of React InstantSearch, change attributeName to attribute
**Why**: because a new major version was released, and this changed
**How**: opening the example in CodeSandbox, seeing the error and updating it here
**Checklist**:

chore(examples): upgrade react instantsearch to v5

---

README.md

Like https://github.com/final-form/react-final-form/pull/191

Official wording of Material-UI

---

README.md
other/ssr/__tests__/index.js
src/index.js

fix(exports): removed statics assignments to default export

---

.all-contributorsrc
README.md
other/react-native/__tests__/__snapshots__/render-tests.js.snap
src/__tests__/__snapshots__/downshift.aria.js.snap
src/__tests__/__snapshots__/downshift.get-item-props.js.snap
src/__tests__/__snapshots__/downshift.get-label-props.js.snap
src/__tests__/downshift.aria.js
src/__tests__/downshift.get-label-props.js
src/downshift.js
src/utils.js

**What**:
Follows #283.
This makes downshift follow the recommended approaches listed here:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html
**Why**:
There are a couple minor violations of the ARIA spec, such as the requirement that an element with a role of `textbox` (an `input` element) be a child of the main `combobox` element. The `aria-expanded` attributes also belong there instead of on the input.
Additionally, there are some roles (`listbox` which belongs on the menu, and `option` which belongs on each item) that are added.
**How**:
Mostly, this follows existing patterns. I've added a `getMenuProps` function which is designed to be called once on the element containing the list of items.
**Checklist**:

ARIA Updates to Match W3C Recommendations

---

typings/index.d.ts

**What**: fixed issues with type signatures mentioned in #391
**Why**:
**How**:
**Checklist**:
Also moved some signatures to be in the same order as in JS file

391 fix type signatures

---

README.md

**What**:
Adds info about how to use Downshift with React Native.
**Why**:
Closes out discussion in #185 
**How**:
Experience using Downshift on React Native 😉
**Checklist**:
* [n/a] Tests
* [n/a] Added myself to contributors table
I'd love some feedback about what else to include here!

Add React Native information to the README

---

typings/index.d.ts

**What**: Minor update to typings
**Why**: Calling `resetIdCounter` seems to be required when doing server rendering, but wasn't present in the typings yet.
**How**: added the function declaration.
**Checklist**:

Add resetIdCounter to typings

---

package.json

**What**: Upgrades kcd-scripts
**Why**: Mostly to get the neat new features from semantic-release.
**How**: Changing the version in package.json
**Checklist**:

chore: upgrade kcd-scripts

---

README.md
typings/index.d.ts

**What**: Add typings for onOuterClick
**Why**: onOuterClick is receiving stateAndHelpers but it's missing in typings
**How**: Add stateAndHelpers: ControllerStateAndHelpers
**Checklist**:
* [ x] Documentation
* [x ] Ready to be merged

add typings for onOuterClick

---

flow-typed/npm/downshift_v2.x.x.js.flow
package.json

**What**: Even more precise type signatures for Flow
**Why**: To increase Flow coverage
**How**: declared return type using parametrised types
**Checklist**:
* N/A Documentation
* N/A Added myself to contributors table
This is not ready to merge. Just curious what do you think about this approach.

[#23] more precise types

---

src/__tests__/downshift.lifecycle.js
src/__tests__/downshift.props.js
src/downshift.js

**What**: #426 
**Why**: To ensure consistent behaviour across devices.
**How**: Adding a `touchstart` event listener to check if the target is anything but downshift.
**Checklist**:

fix: resolve iOS touch blur issue

---

README.md

**What**:
Remove the use of renderProps and use functional child; Toward #433 
**Why**:
Because of #433
**Checklist**:

Recommend functional child method instead of renderProps

---

src/__tests__/downshift.get-button-props.js
src/downshift.js

**What**:
Not run button_handleClick setTimeout for testing so it's not necessary to mock the timers.
**Why**:
See my issue
https://github.com/paypal/downshift/issues/437
**How**:
Check on NODE_ENV variable to disable in test environment.
**Checklist**:
* [not necessary] Documentation

Not run button_handleClick setTimeout for testing

---

flow-typed/npm/downshift_v2.x.x.js.flow
package.json

**What**: added flow-typed to the npm package
**Why**:
**How**:
**Checklist**:

Add flow-typed to files

---

.all-contributorsrc
README.md
package.json

**What**:
Update peerDependencies
**Why**:
`prop-types` [requires](https://github.com/facebook/prop-types#compatibility) `React ^0.14.9`
**Checklist**:
I don't know if I added myself correctly to the contributors. You  can just delete me if  you want, no prob for me 🙂

Fix peerDependencies to be compatible with 'prop-types' package

---

typings/index.d.ts

**What**:
added `null` type to control props
**Why**:
`null` can be passed to control props, as per the actual implementation.
**How**:
change the `index.d.ts` file.
**Checklist**:

[index.d.ts] allow passing null to control props

---

src/__tests__/downshift.get-button-props.js
src/downshift.js

**What**:
Keyboard events on the toggle button works as you would expect. Pressing space or enter should toggle the menu. Fixes #471
**Why**:
To provide a better experience for users that only uses the keyboard for navigation.
**How**:
I added a `onKeyUp` event listener which only runs `event.preventDefault()` to prevent Firefox from firing both the `keyDown` and the `click` event when you press the spacebar.
I also modified the `Enter` handler in the `keyDownHandlers` so it's now possible the properly toggle menu just by pressing the `Enter` key. Before you would only be able to open the menu. I did this by adding a check if `highlightedIndex` is set before we try to select the highlighted item.
**Checklist**:

fix: handle toggle button keyboard events properly (#471)

---

.github/ISSUE_TEMPLATE.md

**What**:
Bolding the titles in the `ISSUE_TEMPLATE.md`
**Why**:
To provide a better overview and match the PR template
**How**:
Bolding the titles
**Checklist**:

Update the ISSUE_TEMPLATE formatting

---

package.json
src/__tests__/downshift.aria.js
src/__tests__/downshift.focus-restoration.js
src/__tests__/downshift.get-button-props.js
src/__tests__/downshift.get-input-props.js
src/__tests__/downshift.get-item-props.js
src/__tests__/downshift.get-label-props.js
src/__tests__/downshift.lifecycle.js
src/__tests__/downshift.misc-with-utils-mocked.js
src/__tests__/portal-support.js
src/__tests__/utils.reset-id-counter.js

**What**:
Upgrade `react-testing-library` to the latest version.
**Why**:
Keeping things up to date. Also the v4 API of `react-testing-library` is a bit cleaner and easier to grasp, so it will be easier for new contributors to add/fix tests.
**How**:
Installed the latest version and migrated the current tests to follow the new API (replace `Simlulate` with `fireEvent` etc).
The only issue I ran into was that I had to run `cleanup` in the `setup` function inside `src/__tests__/utils.reset-id-counter.js`. There might be a better way to solve this that I'm unaware of?
**Checklist**:

Upgrade react-testing-library to v4

---

stories/examples/apollo.js
stories/package.json

**What**:
Update the Storybook stories dependencies to the latest versions. With the exception of `react-popper`, they changed the API in v1 and I was unsuccessful in finding a nice way to integrate it, so I left it for now. See discussion [here](https://github.com/FezVrasta/react-popper/issues/190) and here is a codesandbox of a solution I wasn't really happy with https://codesandbox.io/s/oq9pj2288q
**Why**:
Provide up to date examples for people that's unfamiliar with the library.
**How**:
Updating was pretty straight-forward, the only code I had to edit was the Apollo example. I also removed an unused dependency (`throttle-debounce`).
I was thinking if we should add a `shared.js` similarly to how you did in your `downshift-examples` repo, to keep some style consistant etc. Or should we …

Upgrade Storybook stories dependencies

---

package.json

**What**:
Fix failing Cypress tests
**Why**:
Latest version of Cypress introduced issues when calling `.blur()` on elements inside iframes.
**How**:
Downgrade and lock the Cypress version to 3.0.1. We could have used the `force` option as well but I felt like downgrading was the better option for now.
I've created an issue for this on their repo https://github.com/cypress-io/cypress/issues/2124
When this gets fixed or a good workaround is available we should unlock the version number again.
**Checklist**:

Downgrade cypress 

---

stories/examples/apollo.js
stories/package.json

update getItemCount to have only return statement
A function must have one return statement as per Code Complete standard.
What: Updated getItemCount() to have one return statement
Why: It is easier to understand the flow of the function and improved readability
How:
Added only one return statement and reduced lines of code
Checklist:
Documentation
Tests
Ready to be merged
Added myself to contributors table

update getItemCount to have only return statement

---

package.json

**What**:
Add storybook:install to setup script
**Why**:
Not having storybook dependencies installed resulted in lint errors on validate
(https://github.com/paypal/downshift/issues/501)
**How**:
Add storybook:install to setup script
**Checklist**:

chore: Add storybook:install to setup script (#501)

---

src/downshift.js
src/utils.js

**What**:
Fixed some formatting and removed unnecessary `eslint-ignore` comments
**Why**:
Keeping the code base clean and readable
**How**:
Same as *what*
**Checklist**:

 Formatting and remove unnecessary eslint-ignore comments

---

src/downshift.js

**What**:
Replace inline noop with noop function from `utils.js`
**Why**:
Keeping things consistent and reuse code we already have
**How**:
I switched `() => {}` to `noop` on the `defaultProps` properties
**Checklist**:

Replace inline noop with one from utils

---

package.json

**What**:
Upgrade `serve` dependency
**Why**:
Get rid of upgrade notice and keeping dependencies up-to-date
**How**:
Upgrading dependency
**Checklist**:

Upgrade serve dependency

---

typings/index.d.ts

**What**:
add touchStart to stateChangeTypes
**Why**:
I made a pull request earlier for https://github.com/paypal/downshift/issues/508, but missed one place that needs to add touchStart
**How**:
**Checklist**:
- [X ] Ready to be merged

fix(TS): add touchStart to stateChangeTypes

---

README.md

**What**: docs: add example links
**Why**: The module example links should be working now.
**How**: Using Codesandbox's share UI to generate the links and pasting them in here.
**Checklist**:

docs: add example links

---

README.md

**What**: add youtube link for a devtip on how to contribute to examples
**Why**: So people know how to contribute to examples
**How**: added a link to the examples in the README
**Checklist**:

docs: add youtube link

---

src/downshift.js

**What**:
Don't call the `updateStatus` method at all in RN
**Why**:
No reason why we would want that (that I can tell), also less code to execute
**How**:
Moved the RN if statement to where we call the `updateState` method instead of having the check inside that function.
**Checklist**:

Don't make unnecessary calls to updateStatus in React Native

---

.size-snapshot.json
CONTRIBUTING.md
package.json
src/__tests__/downshift.lifecycle.js
src/utils.js
stories/.babelrc
stories/examples/react-popper.js
test/basic.test.js
test/custom.test.js

**What**:
Upgrades `kcd-scripts` and makes necessary changes (mostly linting)
**Why**:
Keeping up-to-date
**How**:
Upgrade dep and run `npm run validate` to find  eslint errors etc. 
**Checklist**:

Upgrade kcd-scripts

---

.size-snapshot.json
package.json

**What**:
Upgrade `kcd-scripts` and enable size snapshots
**Why**:
Keeping same functionality
**How**:
Add `--size-snapshot` argument on build
**Checklist**:

chore: upgrade kcd-scripts and enable size-snapshot

---

.size-snapshot.json
package.json

fix: bumped kcd-scripts to keep dependencies imported instead of bundled

---

.size-snapshot.json
src/__tests__/__snapshots__/downshift.get-item-props.js.snap
src/__tests__/downshift.get-item-props.js
src/__tests__/downshift.get-label-props.js
src/__tests__/downshift.get-menu-props.js
src/__tests__/downshift.get-root-props.js
src/__tests__/downshift.misc.js
src/downshift.js
src/utils.js

Exploration of https://github.com/paypal/downshift/issues/452#issuecomment-412457953

chore: remove runtime validations for prod builds

---

package.json
src/__tests__/downshift.get-item-props.js

**What**:
Upgrade react-testing-library
**Why**:
Staying up-to-date
**How**:
Upgrade and change how we set value on input fields
**Checklist**:

chore(deps): upgrade react-testing-library

---

stories/examples/basic.js

**What**:
Update `examples/basic.js` to have better a11y.
**Why**:
Make sure we run e2e tests against code that we advocate in the readme.
**How**:
Use `getMenuProps` and always render the menu.
I'm also thinking if we should remove all the examples that are not used for testing now, since most have migrated to `downshift-examples`. It could cause confusion for users when there is "outdated" examples here and they don't notice the code sandbox. 
**Checklist**:

chore: update basic example to have better a11y

---

typings/index.d.ts

**What**:
Made types more accurate.
**Why**:
**How**:
**Checklist**:

Made types more accurate

---

other/react-native/__tests__/__snapshots__/render-tests.js.snap
src/downshift.js

See: https://github.com/paypal/downshift/pull/451
Also re-add `onChange`. Question - should there be something in the README about the RN only tests? Is there? Did I miss it?

Update React Native snapshot

---

src/productionEnum.macro.js

**What**:
fixes a small letter transposition in a comment
**Checklist**:

chore: fix misspelling in comment

---

typings/index.d.ts

**What**:
**Why**:
**How**:
**Checklist**:

types: ability to call getRootProps without arguments

---

test/custom.test.tsx
typings/index.d.ts

**What**:
Updated TypeScript typings following new `initial*` properties.
**Why**:
TypeScript users will not be able to use new 3.x.x features otherwise.
**How**:
Update `typings/index.ts` and `test/custom.test.tsx`
**Checklist**:
I tried to add a 3.x.x flow declaration, but I tried to run `flowgen` but the follow error occurred straight away:
```
$ downshift git:(fix/typings) ✗ flowgen typings/index.d.ts
Parsing index
Parsing index failed
{ SyntaxError: `declare export interface` is not supported. Use `export interface` instead. (9:51)
7 |  */
8 |
>  9 | declare type Callback = () => void;declare export interface DownshiftState<Item> {
```
I'm not really used to flow and it's ecosystem, but I would be more then happy to update this PR if somebody have some suggestion on how to proceed.

Update TypeScript files

---

.size-snapshot.json
src/downshift.js

**What**:
**Why**:
**How**:
**Checklist**:

chore(lint): fixed the lint camelcase errors

---

README.md

Mention the experimentation repo in the README.

docs: mention downshift-hooks in the README

---

test/basic.test.js
test/custom.test.js

disabled some eslint lines that fail master.

chore(test): disable lines for eslint

---

src/hooks/useSelect/README.md

change the downshift-hooks link with the downshift example.

docs: fix useSelect try out yourself codesandbox link

---

docs/useSelect/uiLibraries.mdx

Made it a function and used it as useSelect prop and in the rendered code.
Changed codesandboxes already.

docs(uiLibraries): better illustrate how itemToString is used

---

package.json

Revert that library update until I will get feedback on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39394

chore: revert cypress test library update

---

src/hooks/useSelect/__tests__/getLabelProps.test.js
src/hooks/useSelect/index.js

fixes https://github.com/downshift-js/downshift/issues/789

fix(useSelect): getLabelProps returns htmlFor

---

src/__tests__/utils.handle-refs.js
src/downshift.js
src/hooks/useSelect/index.js
src/utils.js

based on the implementation from @kserjey
FYI @migueloller

fix(refs): accept object refs

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
src/__tests__/__snapshots__/downshift.get-root-props.js.snap
src/downshift.js

Now we are using https://github.com/all-contributors/all-contributors-bot to add contributors

docs: remove mentions about add-contributor script

---

package.json
tsconfig.json

**What**:
Update `@testing-library/cypress` to latest (again).
**Why**:
Because staying up to date is neat.
**How**:
Bump dependency version and add `"types": ["cypress"]` to `tsconfig.json` per the Cypress + TypeScript [documentation](https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json).
**Checklist**:

chore(deps): update @testing-library/cypress to v5.0.2

---

src/hooks/useSelect/index.js
src/hooks/utils.js

Fixes https://github.com/downshift-js/downshift/issues/832 case for Firefox.

fix(useSelect): fix Firefox menu close on toggleButton click

---

.github/PULL_REQUEST_TEMPLATE.md

chore: include types in pull request template

---

.size-snapshot.json
src/__tests__/downshift.get-item-props.js
src/__tests__/utils.getNextWrappingIndex.js
src/downshift.js
src/hooks/useCombobox/__tests__/getInputProps.test.js
src/hooks/useCombobox/__tests__/getToggleButtonProps.test.js
src/hooks/useCombobox/__tests__/props.test.js
src/hooks/useCombobox/index.js
src/hooks/useCombobox/reducer.js
src/hooks/useCombobox/utils.js
src/hooks/useSelect/__tests__/utils.test.js
src/hooks/useSelect/index.js
src/hooks/useSelect/reducer.js
src/hooks/useSelect/utils.js
src/hooks/utils.js
src/utils.js

**What**:
Allows disabled items to be skipped by keyboard highlight (arrow keys, home, end, character keys).
**Why**:
To have this scenario properly working.
**How**:
Refactored the utils methods that handle the index generation logic for highlighting. These methods also request `getItemNodeFromIndex` that will tell them if the item is marked as disabled or not.
This method comes from the hooks / component and is sent as parameter to the utils functions.
Test cases:
- find next non-disabled if next is disabled on arrow down.
- find prev non-disabled if prev is disabled on arrow up.
- if not circular and no non-disabled item can be highlighted, index should stay the same.
- if circular, the search for non-disabled item is resumed from first / last item.
- on home/end, if first/last are …

fix(highlightedIndex): do not highlight disabled items by keyboard

---

.size-snapshot.json
docs/hooks/useCombobox.mdx
docs/hooks/useSelect.mdx
src/downshift.js
src/hooks/useCombobox/__tests__/getInputProps.test.js
src/hooks/useCombobox/__tests__/props.test.js
src/hooks/useCombobox/index.js
src/hooks/useSelect/__tests__/props.test.js
src/hooks/utils.js
src/utils.js

Fixes https://github.com/downshift-js/downshift/issues/884 https://github.com/downshift-js/downshift/issues/881

fix(useCombobox): use mouse and touch events to trigger blur

---

src/utils.js

**What**:
fix tiny spelling error

fix spelling error in utils.js

---

.size-snapshot.json
src/hooks/utils.js

**What**: Fixes #874 
**Why**:
**How**: All side effects must called after reducer calculation
**Checklist**:

Fix warning update state transition in hooks

---

.size-snapshot.json
src/hooks/utils.js

Fix #924
**What**: Fixes #924
**Why**: Creates an infinite loop without this change
**How**: Tested this resolved my issue.
**Checklist**:

Do not call onStateChange if the state did not change

---

.size-snapshot.json
src/hooks/useSelect/index.js

**What**:
dispatch should be passed as argument, otherwise closure issues happens
**Why**:
pass dispatch as argument
**How**:
changed useEffect
**Checklist**:
Fixes #922

fix(useSelect): dispatch closure issue on search by key

---

.size-snapshot.json
src/hooks/useCombobox/index.js

**What**:
Fixes #941
**Checklist**:

fix(useCombobox): dispatch ToggleButtonClick before focusing input

---

src/hooks/useCombobox/index.js
src/hooks/useSelect/index.js
src/hooks/utils.js

**What**:
`dispatch` will receive props by default.
**Why**:
`dispatch` needed them anyway so we don't have to wrap the original dispatch every time in every hook with a function that gives it props.
**How**:
**Checklist**:

chore(hooks): apply props by default to dispatch

---

README.md

I just noticed these and thought I'd fix them :)

docs: update kent's blog post URLs

---

src/hooks/useMultipleSelection/README.md
typings/index.d.ts

fix(useMultipleSelection): replace item with selectedItem in typings for `getSelectedItemProps`

---

cypress/integration/combobox.js

**What**:
Menu navigation in cypress tests.
**Why**:
It is failing on CI.
**How**:
Improve the regexes to match the text exactly.
**Checklist**:

chore(cypress): fix menu navigation

---

README.md

**What**:
**Why**:
**How**:
.com -> .app
**Checklist**:

docs: fix netlify links in Readme

---

.size-snapshot.json
README.md
src/hooks/testUtils.js
src/hooks/useCombobox/README.md
src/hooks/useCombobox/__tests__/props.test.js
src/hooks/useCombobox/index.js
src/hooks/useSelect/README.md
src/hooks/useSelect/__tests__/props.test.js
src/hooks/useSelect/index.js
src/hooks/useSelect/utils.js
src/hooks/utils.js
src/utils.js
typings/index.d.ts

**What**:
Adding a11y messages for dropdown status. Details in attached issue.
**Why**:
Align implementations between Downshift and hooks for adding a11y status messages in the DOM.
**How**:
- `useSelect` and `useCombobox` will now have stored `previousResultCount` which will be passed to `getA11yStatusMessage`.
- Status setting function will be called debounced, as in `Downshift`.
- Status setting function will be called at each state change, as in `Downshift`. Previously, in hooks, it was only called on `isOpen` change.
- Default `getA11yStatusMessage` will now check the equality between `resultCount` and `previousResultCount`. If not equal, then it will add the message about the number of elements.
- TS interface `A11yStatusMessageOptions` will no longer have `previousResultCount` as …

feat(hooks): align behavior of a11y status messages between hooks and Downshift

---

docs/hooks/useMultipleSelection.mdx

**What**:
Some small improvements for `useMultipleSelection` docsite example.
**Why**:
Requested here https://github.com/downshift-js/downshift/issues/1012.
**How**:
**Checklist**:
Closes https://github.com/downshift-js/downshift/issues/1012.

docs(useMultipleSelection): improve examples

---

.size-snapshot.json
src/hooks/useCombobox/__tests__/getInputProps.test.js
src/hooks/useCombobox/__tests__/props.test.js
src/hooks/useCombobox/index.js
src/hooks/useCombobox/testUtils.js
src/hooks/useCombobox/utils.js
src/hooks/useMultipleSelection/__tests__/props.test.js
src/hooks/useMultipleSelection/index.js
src/hooks/useMultipleSelection/testUtils.js
src/hooks/useSelect/__tests__/props.test.js
src/hooks/useSelect/index.js
src/hooks/utils.js

**What**:
Reverting the `useState` usage for computing the controlled state and going back to `useReducer` + adding `useEffect` to call onChange handlers.
**Why**:
Fix https://github.com/downshift-js/downshift/issues/1018 and keep the fixes for React warning and inputValue not being updated. https://github.com/downshift-js/downshift/issues/962 https://github.com/downshift-js/downshift/issues/982
**How**:
Going back to previous implementation of the state handlers with useReducer but now calling on change handlers in a useEffect.
Also, for useCombobox, we will check if selectedItem is controlled and has been changed (via props or state) and based on that trigger a state change with the new inputValue.
**Checklist**:
Closes https://github.com/downshift-js/downshift/issues/1018

fix(useControlledState): use reducer + useEffect

---

docs/downshift/downshift.mdx

**What**:
Fixing minor typo in downshift doc
**Why**:
It's a typo
**How**:
Updated typo to what was intended
**Checklist**:

fix typo on downshift doc

---

docs/hooks/useSelect.mdx

**What**: Doc changes
**Why**: To clean up grammar
**How**: Using GitHub's editor
**Checklist**:

docs: improve useSelect documentation in the docsite

---

docs/downshift/downshift.mdx
docs/hooks/useCombobox.mdx
docs/hooks/useMultipleSelection.mdx
docs/hooks/useSelect.mdx
docs/index.mdx

**What**:
**Why**:
**How**:
**Checklist**:

docs: improvements in the docsite

---

src/hooks/useSelect/README.md

**What**: Typo
**Why**:
**How**:
**Checklist**:

inputvalue => inputValue

---

README.md
src/hooks/README.md
src/hooks/useCombobox/README.md
src/hooks/useMultipleSelection/README.md
src/hooks/useSelect/README.md

**What**:
Improves documentation and examples on Github for both the component and hooks.
**Why**:
Mistakes in the documentation / improvements needed.
**How**:
N/A
**Checklist**:

docs: improve the README files

---

src/utils.js

**What**:
Fixes #823 
**Why**:
It's necessary to check for actual fields first, because preact/debug throws error when deprecated fields are used.
**Checklist**:

fix(preact): add support for preact/debug

---

README.md

**What**:
Typo in documentation.
**Why**:
Documentation should be proper.
**How**:
Added a missing character.
**Checklist**:

Fixed typo in documentation

---

.size-snapshot.json
src/hooks/useCombobox/__tests__/getInputProps.test.js
src/hooks/useCombobox/index.js
src/hooks/useSelect/__tests__/getMenuProps.test.js
src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
src/hooks/useSelect/index.js
src/hooks/utils.js
src/utils.js

**What**:
Support virtualization in useCombobox and useSelect.
**Why**:
To allow users to use react-virtual, react-virtualized and react-window with minimum effort.
**How**:
We keep itemRefs in an Object by the ID as key, instead of pushing them in an array.
We also fixed a bug with `highlightedIndex` being returned as 0 on ArrowDown when there are no items available.
**Checklist**:
Fixes https://github.com/downshift-js/downshift/issues/1041.

feat(hooks): allows virtualization for hooks

---

src/hooks/useCombobox/README.md

**What**:
fix a typo in README
**Why**:
**How**:
**Checklist**:

fix typo in README.md

---

README.md

**What**:
Fixed the link to the docsite.
**Why**:
Downshift got a new domain for the docsite.
**How**:
Replace netlify link with the new domain.
**Checklist**:

docs: fix links to the new docs

---

README.md

**What**:
**Why**:
**How**:
**Checklist**:

docs: add link to the docs

---

src/hooks/useCombobox/README.md
src/hooks/useMultipleSelection/README.md
src/hooks/useSelect/README.md

**What**:
Add details about the `ref` optional parameter to the appropriate getter props.
**Why**:
Improve documentation and clarify usage.
**How**:
Add `ref` sections in the Readme where needed.
**Checklist**:

docs(hooks): add getter prop ref documentation

---

README.md
src/hooks/useCombobox/README.md
src/hooks/useMultipleSelection/README.md
src/hooks/useSelect/README.md

**What**:
Refresh the examples and the introduction part of the README.
**Why**:
To improve usage experience.
**How**:
Change README files.
**Checklist**:

docs: refresh the first part of the Readme and examples

---

.size-snapshot.json
package.json
src/__tests__/downshift.aria.js
src/__tests__/downshift.focus-restoration.js
src/__tests__/downshift.get-input-props.js
src/__tests__/downshift.get-item-props.js
src/__tests__/downshift.get-label-props.js
src/__tests__/downshift.get-root-props.js
src/__tests__/downshift.lifecycle.js
src/__tests__/downshift.misc-with-utils-mocked.js
src/__tests__/portal-support.js
src/__tests__/utils.reset-id-counter.js
src/hooks/useCombobox/__tests__/getInputProps.test.js
src/hooks/useCombobox/__tests__/getItemProps.test.js
src/hooks/useCombobox/__tests__/getLabelProps.test.js
src/hooks/useCombobox/__tests__/getToggleButtonProps.test.js
src/hooks/useCombobox/testUtils.js
src/hooks/useMultipleSelection/testUtils.js
src/hooks/useSelect/__tests__/getItemProps.test.js
src/hooks/useSelect/__tests__/getLabelProps.test.js
src/hooks/useSelect/__tests__/getMenuProps.test.js
src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
src/hooks/useSelect/__tests__/props.test.js
src/hooks/useSelect/testUtils.js

**What**:
Update dependencies and fix the unit tests as a result of Testing Library updates.
**Why**:
To be up to date.
**How**:
Update packages and fix breaking errors.
**Checklist**:

chore: update everything

---

.size-snapshot.json
src/hooks/useCombobox/index.js
src/hooks/useMultipleSelection/index.js
src/hooks/useSelect/index.js
src/hooks/utils.js

**What**:
Re-use some hooks based logic.
**Why**:
Code improvement.
**How**:
Abstract some utility hooks-based logic into their own hooks, moved them to utils and reuse them from there.
**Checklist**:

perf(hooks): reuse utility hooks

---

README.md

**What**:
Update the link to downshift's logo svg.
**Why**:
For it to appear.
**How**:
Use link from github.
**Checklist**:

docs: update downshift logo link

---

README.md
package.json
src/hooks/useCombobox/README.md
src/hooks/useMultipleSelection/README.md
src/hooks/useSelect/README.md

**What**:
Updates some links related to downshift-docs and downshift-examples.
**Why**:
Provide relevant links.
**How**:
Change links.
**Checklist**:

docs: update references to examples and docs

---

src/hooks/useSelect/README.md

**What**:
add button type "button" to avoid automatic form submission when using the hook on the form element
**Checklist**:

docs(useSelect): add button type "button" to useSelect docs

---

.size-snapshot.json
src/hooks/useCombobox/index.js
src/hooks/useCombobox/reducer.js

…andleBlur to ensure that items could not be selected by clicking the left arrow key when the dropdown was closed
**What**:
An additional conditional statement was added to prevent a bug where an item could be selected when using useMultipleSelection with useCombobox while the dropdown menu was closed
**Why**:
An issue for this change was made.
**How**:
Additional logic was added to ensure that in order for an item to be selected the dropdown menu must be open.
**Checklist**:
- [ X] Documentation
- [ X] Tests
- [ X] TypeScript Types
- [ X] Flow Types
- [ X] Ready to be merged
Yes.
There was technically an error during the commit to my local branch, but I believe this is due the value of "total" being 0 for test/setup.js, but I could be wrong.

fix(useCombobox): select item on blur only when menu is open

---

README.md
src/hooks/useCombobox/README.md
src/hooks/useMultipleSelection/README.md
src/hooks/useSelect/README.md

**What**:
Improve documentation for itemToString and autocomplete.
**Why**:
To have a better documentation
**How**:
**Checklist**:

docs: improve Readme files

---

src/hooks/useMultipleSelection/README.md

**What**:
Consequence of https://github.com/downshift-js/downshift/pull/1168.
**Why**:
**How**:
**Checklist**:

docs: fix useMultipleSelection import

---

README.md

**What**: :hankey: 
**Why**:
**How**:
**Checklist**:

Remove shit

---

src/__tests__/downshift.get-input-props.js
src/__tests__/downshift.get-item-props.js
src/hooks/useCombobox/__tests__/props.test.js

**What**:
Use .toHaveValue instead of .value).toBe as the rule requests.
**Why**:
Fix the build.
**How**:
Fix the tests.
**Checklist**:

dev: fix build lint step

---

src/utils.js

Fixes [#1155](https://github.com/downshift-js/downshift/issues/1155)

fix(isOrContainsNode): check if child is instance of Node

---

README.md

I noticed a typo
**What**: Fix typo convers to covers
**Why**: Typo
**How**: Keyboard
**Checklist**:
- [x ] Documentation
- [ x] Ready to be merged

Fix typo convers to covers

---

package.json

**What**: Bumping `compute-scroll-into-view` from `1.0.16` to `1.0.17`
**Why**: A fix was made to prevent checking `clientHeight` of `null`. https://github.com/stipsan/compute-scroll-into-view/pull/784
**How**: These changes were made in the dependency.
**Checklist**:
I have forced a resolution using Yarn's resolution feature to test the bump in my repository.

Bump compute-scroll-into-view

---

cypress/integration/combobox.js
package.json
src/__tests__/downshift.focus-restoration.js
src/hooks/useCombobox/testUtils.js
src/hooks/useMultipleSelection/testUtils.js
src/hooks/useSelect/testUtils.js

chore(dependencies): update everything

---

src/utils.js

**What**:
**Why**:
**How**:
**Checklist**:

docs: typo in utils

---

package.json

**What**: Add tslib dependency in pacakge.json.
Closes https://github.com/downshift-js/downshift/issues/1309
**Why**: @rollup/plugin-typescript has tslib as a peer dependency and requires to be installed separately. The dependency not being there is currently causing an [issue](https://github.com/downshift-js/downshift/issues/1309). 
**How**: Added the dependency and ran npm run validate
**Checklist**:
- [N/A] Documentation
For futuure PR: I don't have much idea about tslib but looking at the package, it would be a good improvement to use it in downshift-js as well.

fix(TS): add tslib as a dependency

---

README.md
babel.config.js
src/hooks/useCombobox/README.md
src/hooks/useSelect/README.md

**What**:
Replacement for https://github.com/downshift-js/downshift/pull/1379. Thank you @Rendez !
**Why**:
**How**:
**Checklist**:

docs: fix ARIA 1.1 links for combobox and select

---

docusaurus/pages/index.js
docusaurus/pages/useMultipleCombobox.js
docusaurus/pages/useMultipleSelect.js
docusaurus/pages/useSelect.js
package.json

**What**:
Add docs pages for useMultipleSelection, combobox + select, bump docusaurus version.
**Why**:
To have an easier time testing the hook.
**How**:
Doc pages for usemultipleseleciton + select/combobox.
**Checklist**:

dev: add docs for multiple selections

---

src/hooks/__tests__/utils.test.js
src/hooks/utils.js

**What**:
Fixes https://github.com/downshift-js/downshift/issues/1331.
Fixes https://github.com/downshift-js/downshift/issues/1370.
**Why**:
Do not account controlled, initial or default values if they are undefined, in order to get initial/reset state value.
**How**:
Check for undefined instead of key in object.
**Checklist**:

fix(hooks): do not accept undefined as initial values

---

src/hooks/reducer.js
src/hooks/useCombobox/__tests__/getItemProps.test.js
src/hooks/useCombobox/index.js
src/hooks/useCombobox/testUtils.js
src/hooks/useSelect/__tests__/getItemProps.test.js
src/hooks/useSelect/index.js
src/hooks/useSelect/testUtils.js

**What**:
Fixes https://github.com/downshift-js/downshift/issues/1385.
**Why**:
**How**:
**Checklist**:

fix(hooks): remove highlight when hovering disabled item

---

CONTRIBUTING.md
other/TYPESCRIPT_USAGE.md

**What**:
The link "[How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)" in CONTIBUTING.md is invalid.
**Why**:
Clean documents are worth like clean codes.
**How**:
The link is replaced with the new link: https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github
**Checklist**:
Hi!
Downshift excites me.
In particular, great ARIA support makes me happy.
Thanks for developing!
I am happy to help with the downshift project even just a little bit.

docs: update a link in CONTRIBUTING.md

---

README.md
docusaurus/pages/index.js
docusaurus/pages/useCombobox.js
docusaurus/pages/useMultipleCombobox.js
docusaurus/pages/useMultipleSelect.js
docusaurus/pages/useSelect.js
src/hooks/MIGRATION_V7.md
src/hooks/useCombobox/README.md
src/hooks/useMultipleSelection/README.md
src/hooks/useSelect/README.md

**What**:
Changes from https://github.com/downshift-js/downshift/pull/1431 and https://github.com/downshift-js/downshift/pull/1424.
Updates all the links.
Updates the Usage examples to include actual running code.
**Why**:
Improve downshift documentation.
**How**:
Update links.
Take usage examples from the ones used in the testing docsite.
**Checklist**:

docs: improvements overall

---

docusaurus/pages/combobox.js
docusaurus/pages/useCombobox.js
docusaurus/pages/useMultipleCombobox.js
docusaurus/pages/useMultipleSelect.js
docusaurus/pages/useSelect.js
docusaurus/utils.js
package.json
src/utils.js

**What**:
**Why**:
Fixes https://github.com/downshift-js/downshift/issues/1449.
**How**:
**Checklist**:

feat: update scrollIntoView library

---

README.md

**What**:
Quick edit of the README

docs: update README.md typo

---

src/hooks/useSelect/index.js

**What**:
Conditionally apply mouse and key handlers in `useSelect` for React and React Native.
**Why**:
React and React Native have different names for handlers.
**How**:
Check in getToggleButtonProps if it's react native, then add only onPress with toggleButtonHandleClick. Otherwise, add the onClick and onKeyDown as before.
Check in getItemProps if it's react native, then add only onPress with itemHandleClick. Otherwise, add the onClick as before.
**Checklist**:

feat(useSelect): react native handlers

---

README.md
src/hooks/README.md

**What**:
Add axe-con 2021 recording and some other mentions to the docs.
**Why**:
Better development experience.
**How**:
**Checklist**:

docs: axe-con recording

---

other/ssr/__tests__/index.js
package.json

**What**:
**Why**:
**How**:
**Checklist**:

dev: fix build by installing missing dev deps

---

src/hooks/MIGRATION_V8.md

**What**:
**Why**:
**How**:
**Checklist**:

docs: run doctoc in readme files

---

package.json
src/hooks/MIGRATION_V8.md
typings/index.d.ts

**What**:
Replace GestureResponderEvent with BaseSyntheticEvent.
**Why**:
Remove the need for react-native types.
**How**:
Replace the type, remove the package.
**Checklist**:

fix(types): remove GestureResponderEvent

---

.github/workflows/validate.yml

**What**:
Update the node version for the release job in GH actions.
**Why**:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-1.html#es2020-and-nodejs-1417-as-minimum-runtime-requirements
**How**:
Bump the version to 16.
**Checklist**:

dev: update node to 16 in release job

---

src/__mocks__/set-a11y-status.js
src/__tests__/downshift.lifecycle.js
src/__tests__/set-a11y-status.js
src/downshift.js
src/hooks/MIGRATION_V9.md
src/hooks/testUtils.js
src/hooks/useCombobox/README.md
src/hooks/useCombobox/__tests__/props.test.js
src/hooks/useCombobox/index.js
src/hooks/useCombobox/utils.js
src/hooks/useMultipleSelection/README.md
src/hooks/useMultipleSelection/__tests__/props.test.js
src/hooks/useMultipleSelection/index.js
src/hooks/useMultipleSelection/testUtils.js
src/hooks/useMultipleSelection/utils.js
src/hooks/useSelect/README.md
src/hooks/useSelect/__tests__/props.test.js
src/hooks/useSelect/index.js
src/hooks/useSelect/utils.ts
src/hooks/utils.js
src/set-a11y-status.js
typings/index.d.ts

**What**:
**Why**:
Closes https://github.com/downshift-js/downshift/issues/1244.
**How**:
**Checklist**:

feat(getA11yStatusMessage): simplify the a11y message in hooks
